pyproj4/pyproj

lib/pyproj/__init__.py

In Python 2.7 "str" and "unicode" are two different type of objects.
If proj4 init *unicode* string is provided to Proj object it will treat it as a dictionary and fail.
Checking for whether the string is 'str' or 'unicode' solves the problem.

Check if proj init string is a unicode string

---

setup.py

I suggest using setuptools, rather than raw distutils, in the setup.py.
setuptools is pretty much ubiquitous these days, so it's not likely to be a problem. And pip requires setuptools, so anyone doing ``pip install`` is guaranteed to have it.
But it's a better option, particularly on Windows, where recent setuptools can properly find the "MS VS compiler for python2.7", whereas distutils cannot.

Add setuptools to setup.py

---

lib/pyproj/__init__.py
unittest/test.py

This is a patch to `transform()` to check if p1 and p2 are instances of the Proj class.  Tests are also provided for unittest.
Hopefully, resolving issue #8.

Patch for transform to resolve Issue #8

---

lib/pyproj/__init__.py

As the code uses a dict to pass parameters, it tries to split
every parameter into name and value. If a valueless parameter
is given, ex: +no_defs, it breaks the split.
We can safely ignore any parameter that is not +a and +b, so
the easiest workaround for this issue is to just ignore the
problematic parameter

Don't pass valueless parameters to Geod

---

lib/pyproj/__init__.py

This line in `Proj.__new__()` to test if `projparms` is a string was always true because `or unicode` statement short circuited the logic. This would cause projparms as a dictionary to be passed to projstring.  That caused the projstring.count() to fail, because dictionaries don't have that function.
I recoded this so that the six package is NOT needed.
This problem was discovered because the unittest testProjAwips221 was failing.

Fix for string type test

---

lib/pyproj/__init__.py

Removed documentation about this function accepting ndarray of shape n,2.  This addresses some of the concerns raised in issue #4 .

Updated __call__() docstring about ndarray n,2

---

unittest/test.py

Removing + (plus signs) in unit test

---

_proj.pyx
unittest/test.py

add a check to ensure inverse projection is defined, before calling it (needed to prevent segfaults for proj versions 4.9.2 and before).
This solves issue #43 on my system. The inverse call now throws a proper python exception if the inverse projection is not defined, in the case that the module is build without bundled proj sources.

fix segmentation fault

---

setup.py

This makes _proj.pyx have the only copy of `__version__`.  The with statement requires Python 2.5.  If desired, I'll refactor the code for Python 2.4 support.  My intent is to remove one step from the process of updating the version number.
Here's what pip outputs:
```
C:\Users\mcochran\github\pyproj>pip install .
Processing c:\users\mcochran\github\pyproj
Installing collected packages: pyproj
Running setup.py install for pyproj ... done
Successfully installed pyproj-1.9.5.1
```
Looks like pip recognizes the version number.

setup.py: Parse version from _proj.pyx

---

.travis.yml
unittest/test.py

Had to install unittest2 for Python 2.6 in order to support tests in the tests in class TypeError_Transform_Issue8_Test.  `from __future__ import with_statement` was added for Python 2.5 support.

Travis-CI: Add Python version 2.6 to testing

---

lib/pyproj/__init__.py

This pull request increases the Python version to be inline with the latest release of Cython 0.23.4.  Which apparently gives a pragma error when compiled with Python version below this.  See [_proj.c line 8](https://github.com/jswhit/pyproj/blob/master/_proj.c#L8).  Another way to resolve this would be to regenerate the Cython code using version 0.20.x.
Also, there are with statements in the current code, which is enabled via a \__future__ statement in 2.5.x.
Python 2.6's support ended in October 29, 2013 with the [release of Python 2.6.9 PEP-361](https://www.python.org/dev/peps/pep-0361/).  Other project have even been getting rid of Python 2.6 support.
Travis-CI currently allows testing on Python 2.6.  There is a separate PR #51 to add that testing.  Travis-CI makes it easier to …

Increase required Python version to 2.6+ & 3.2+

---

appveyor.yml
ci/appveyor/run_with_env.cmd

This adds automated testing for Windows.
[Here is the  builds](https://ci.appveyor.com/project/micahcochran/pyproj/build/1.0.14), which passes all tests.
Appveyor will need to be enabled on the appveyor.com website, which is similar to the process of turning on Travis for repositories.

Add Appveyor support for build tests on Windows.

---

setup.py

The additional debug output of `setup.py` might screw up some build tools that parse it. In particular, the missing newline after the ["executing" log](https://github.com/jswhit/pyproj/blob/master/setup.py#L91) makes it hard to gather package information.
Old:
```bash
jakob@MosEisley % python2 setup.py --name
using bundled proj4..
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
Output Binary File Format: ctable2
executing /home/jakob/playground/pyproj/nad2bin lib/pyproj/data/null < …
```

Allow package information parsing and print build debug info to stderr

---

_proj.pyx
lib/pyproj/__init__.py
unittest/test.py

Returning a pyproj.Proj instance instead of the underlying base class _proj.Proj in pyproj.Proj.to_latlong function feels more intuitive.
This patch adresses a bug as well in pyproj.transform's function check. See Issue #53
**Updated from #54, #56 and #66**
This is exactly the same as #72 but based on the removal of _proj.c file. (#70)
Sorry about the multiple pull requests...

Change Proj.to_latlong in order to return an instance of pyproj.Proj (clean)

---

.travis.yml
appveyor.yml
lib/pyproj/__init__.py

This was found during a commit of PR #78 that a doctest failed, but passed in Travis.  This change will cause Travis to fail when a doctest fails. 
Also, remove duplicate lines in doctest for Geod class.

Doctest: add exit code for Travis of the number of failed doctests.

---

lib/pyproj/__init__.py
unittest/test.py

The unittests have different tests for PROJ.4 versions before and after the inverse hammer patch was integrated into the main PROJ.4 repository.  Fixes a doctest error for PROJ.4 version 4.9.2.  Retain similar testing method.
This was discovered during PR #82 and "cherry picked" from it.

TEST: Move inverse hammer test from doctest to unittest.

---

_proj.pyx
lib/pyproj/__init__.py
unittest/test.py

This is a redo of PR #63 without conflicts and all the extra commits.  This adds representations for Geod and Proj classes that are a little more user friendly when using the python console.
Also, this adds a Geod.\__eq\__ function, which allows comparison between Geod objects.  I had issue #15 in mind when writing this, but I'm not really sure that this is really useful. 
In order for Geod.\__repr\__ function to work as written, issue #64 had to be fixed (which was done in PR #65).

Add __repr__ and __eq__ functions

---

.travis.yml

Python 3.3 is at end of life on 2017-09-29. Python 2.6 has been end of life for a while.

No longer test Python 2.6 & 3.3, add 3.6.

---

README.md

Several issues report problems with using `pip install pyproj`. A workaround is using the latest version from Github.
Some issues with pip problems: #141 #136 #133 #132 #130 #59 #25 #13 #9.

Add installation instructions for pip

---

setup.py

The clean target is called outside the build chroot when building
Debian packages. Only inside the chroot will dependencies be available.
Cythonize changes the source tree which should only happen in build target.

Perform minimal actions in clean target.

---

unittest/test.py

Remove cruft in unittest/test.py from supporting old Python and old PROJ versions.

Remove cruft from unsupported software versions

---

setup.py

In check_proj_version() add installed PROJ version to error message, return proj_version, use pkg_resources.parse_version() to provide a more featureful Version object.
After @snowman2 asked about the matter, so I just dug into it.  This is the [better Version object](https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python) because distutils LooseVersion and StrictVersion are poorly documented and support the superceeded PEP 386.  pkg_resources.parse_version follows PEP 440, and pkg_resources is provided by setuptools.
The returned proj_version value could be useful if there needs to be some other steps that have to be taken for future version of PROJ, while supporting older PROJ versions with operators such as 
`version >= parse_version('6.1.0')`.
So on my …

Update setup.py PROJ version checking 

---

pyproj/transformer.py

Replace Beijing 1954 with New Beijing that superseded it.
---
This must be passing for others but my installation of PROJ 6.0.0 does not like this:
```
echo 116.366 39.867 | cs2cs epsg:4214 epsg:4326 
*	* inf
```
Seems easier to fix like this, hope that is OK.

avoid transformer docstring test failure due to CRS

---

pyproj/_proj.pyx
pyproj/_transformer.pyx

As seen here: https://github.com/pyproj4/pyproj/issues/207#issuecomment-474667389.
Already used here:
https://github.com/pyproj4/pyproj/blob/b1eac98bef754edbb28fe8b080e9f8421ed61cee/pyproj/_transformer.pyx#L157

convert PROJ error messages from bytes to strings

---

unittest/test.py

Use unittest.TestCase.subTest() instead of nose2.tools.params().
test.py will now run and all tests execute without nose2, but
ForwardInverseTest cannot be used with Python 2.
---
A trade-off here, depends what is most important.

replace use of nose2.tools in test.py

---

pyproj/_transformer.pyx
pyproj/transformer.py
unittest/test_transformer.py

Sometimes errors may not be caught in the default way, this is a fallback method for catching them.

added check for error count in transformations

---

pyproj/_transformer.pyx
pyproj/transformer.py
unittest/test_transformer.py

fixed projection equivalence testing & projecting with time transformations

---

test/test_datadir.py

Previously it was not removing the env var if it used to be there.

fix proj_env in data dir tests

---

.travis.yml

OSX was reverting to using Python 2.7.  Apparently, it needs all three numbers specified, so "3.6.8".
sudo: true is no longer needed on xenial.

Travis-CI: peg osx to a specific PY version

---

sphinx/conf.py

No custom static files are used.
Avoid warning about html_static_path entry not existing.

don't define unused Sphinx html_static_path

---

test/test_awips221.py
test/test_pickle.py

Fix warnings and prepare for Python 3.8.

replace deprecated time.clock() in tests

---

pyproj/_crs.pxd

Closes https://github.com/pyproj4/pyproj/issues/254
The `CRS` had an unused and not set attribute `proj_version`.

CLN: remove unused _CRS.proj_version from pxd file

---

pyproj/cf1x8.py
pyproj/crs.py
test/test_crs_cf.py

Addresses #226 
This will need a good review.
I am unsure about what the CF `unit` mapped to. It is either `units` or `vunits`. I am guessing `vunits` at the moment, but it is only a guess.
Others I think are just another maping to `datum`, but not sure. Maybe there is a `vdatum` in PROJ I am missing.
- geoid_name (OGC WKT VERT_DATUM - ex GEOID12B)
- geopotential_datum_name (OGC WKT VERT_DATUM - ex NAVD88)

added CRS mapping to/from CF 1.8; added to_proj4_dict

---

pyproj/crs.py
pyproj/geod.py
pyproj/proj.py

document attributes on CRS,Geod,Proj classes

---

.travis.yml
appveyor.yml

Alternative / easier, temporary fix for https://github.com/pyproj4/pyproj/pull/282 by just pinning pip, since they are still discussing whether to fix this on the pip side (https://github.com/pypa/pip/issues/6434)

CI: pin pip < 19.1 to avoid breakage of editable install

---

MANIFEST.in

Avoid warnings for files not found.
---
I have tested `setup.py sdist` (Python 3.7.3, setuptools 40.6.3) but my interest was removing warnings - please check it creates the required tarball for releases from your workflow.

remove from MANIFEST.in obsolete and automatically included files

---

pyproj/enums.py
setup.py

Thought to make this dependency conditional, like before for enum34 was also done.

Only require aenum for python < 3.6 versions

---

test/test.py

```
ERROR: testProj4Version (__main__.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test/test.py", line 16, in testProj4Version
assert re.match(r"\d+\.\d+", awips221.proj_version)
File "/usr/lib/python3.7/re.py", line 173, in match
return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

fix testProj4Version for Proj.proj_version being an integer

---

docs/api/crs.rst
docs/history.rst
pyproj/_crs.pxd
pyproj/_crs.pyx
pyproj/_geod.pxd
pyproj/crs.py
test/test_crs.py

Fixes summary:
- added 'is_proj'; 
- fixed case in 'to_dict' with 'to_proj4' returning None
- keep `no_defs` as it does not hurt anything in current code and it preserves backwards compatibility with older versions
- made public properties on C classes readonly
ping @djhoese

pyproj.crs updates/fixes (is_proj/to_proj4/to_dict/from_string)

---

docs/history.rst
pyproj/_crs.pyx
pyproj/_datadir.pxd
pyproj/_datadir.pyx
pyproj/_transformer.pyx
pyproj/datadir.py

Before:
```
Exception ignored in: 'pyproj._datadir.get_pyproj_context'
Traceback (most recent call last):
File "/home/snowal/scripts/pyproj/pyproj/datadir.py", line 99, in get_data_dir
"Valid PROJ data directory not found."
pyproj.exceptions.DataDirError: Valid PROJ data directory not found.Either set the path using the environmental variable PROJ_LIB or with `pyproj.datadir.set_data_dir`.
proj_create: Cannot find proj.db
proj_create: no database context specified
...
```
After:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/snowal/scripts/pyproj/pyproj/crs.py", line 302, in __init__
super(CRS, self).__init__(projstring)
File "pyproj/_crs.pyx", line 1308, in pyproj._crs._CRS.__init__
self.projctx = get_pyproj_context()
File "pyproj/_datadir.pyx", …
```

update data dir exception handling to prevent ignoring errors

---

docs/history.rst
pyproj/cf1x8.py
pyproj/crs.py
test/test_crs_cf.py

CRS.to_cf export transverse mercator parameters for UTM zones

---

.travis.yml
docs/history.rst
docs/index.rst
pyproj/_crs.pyx
pyproj/_transformer.pyx
pyproj/compat.py
pyproj/crs.py
pyproj/enums.py
setup.py

Minimum supported Python version 3.5; removed aenum dependency

---

docs/history.rst
pyproj/_crs.pxd
pyproj/_crs.pyx
pyproj/_datadir.pxd
pyproj/_datadir.pyx
pyproj/_proj.pxd
pyproj/_proj.pyx
pyproj/_transformer.pyx
pyproj/datadir.py
pyproj/proj.pxi
test/test_datadir.py

updated to only have one PJ_CONTEXT per pyproj session

---

.travis.yml
appveyor.yml
docs/installation.rst
pyproj/_geod.pxd
pyproj/_geod.pyx
pyproj/_proj.pyx
pyproj/_transformer.pyx
pyproj/proj.pxi
setup.py

Currently not possible. Only one thread can use one PJ* at a time. https://github.com/OSGeo/PROJ/blob/f567ee4b8739505716cbb000093d78678a97b170/src/iso19111/c_api.cpp#L338
It was unstable. See #380

remove parallel omp cython code & parallel CICD matrix items

---

pyproj/crs.py
test/test_crs.py
test/test_datum_shift.py
test/test_proj.py
test/test_transformer.py

Decided against promoting to FutureWarning at this stage.  Probably make it a FutureWarning around the time of #365 or when a PROJ release with its removal is more imminent.

made init= syntax use DeprecationWarning instead of FutureWarning

---

docs/history.rst
pyproj/__init__.py
pyproj/_datadir.pxd
pyproj/_datadir.pyx
pyproj/datadir.py
test/test_datadir.py

I couldn't reproduce the segfault, so this is my best guess.

delay checking for pyproj data directory until importing pyproj

---

docs/history.rst
pyproj/_datadir.pyx

FIX: address issue where PROJ core dumps on proj_create with +init= when global context does not have data directory set

---

docs/history.rst
pyproj/_crs.pyx
test/test_crs.py

Add checks for unititialized pyproj.crs objects to prevent core dumping

---

pyproj/_crs.pyx

The lintian QA tool reported a spelling error for the Debian package build of 2.4rc0:
* intialized -> initialized

Fix spelling errors.

---

pyproj/_proj.pyx

otherwise 32-bit pyproj may show strange errors
Closes #481 
I found this one by trial and error, and to me it seems this is either an undocumented feature of libproj or just a plain bug. Anyway, for pyproj this solved the test failures that I observed on 32-bit.
I now updated the pull request to your suggestion to apply proj_coord() outside the loop in the cdef statement. Tested again, and can confirm that this implementation also solves the 32-bit problem.

init all 4 fields in the the input PJ_COORD variable before use

---

docs/history.rst
pyproj/_crs.pyx
pyproj/crs.py
test/test_crs.py

This is a potential concept for the ignore axis order feature. The other option could be to add a `method` kwarg with the `exact`, `equvalent`, and `ignore_axis_order` options.

ENH: Added 'pyproj.crs.CRS.equals' with 'ignore_axis_order' kwarg

---

docs/api/crs.rst
docs/history.rst
pyproj/_crs.pyx
pyproj/crs.py
test/test_crs.py
test/test_crs_json.py

Currently some roundtrips using `to_json/from_json` won't work: https://github.com/OSGeo/PROJ/issues/1818
Also, support for the WKT form is missing: https://github.com/OSGeo/PROJ/issues/1819

added from_json, from_json_dict, and from_string methods to CoordinateSystem added CoordinateSystem to pyproj.crs namespace

---

docs/history.rst
pyproj/_crs.pxd
pyproj/_crs.pyx
pyproj/crs.py
test/test_crs.py
test/test_transformer.py

Added from_user_input() method to Datum, Ellipsoid, CoordinateSystem, CoordinateOperation, PrimeMeridian

---

pyproj/_crs.pyx

- default from_name to search for all authorities
Reasoning: it is used in `from_string` and `from_user_input`, so don't want to restrict it prematurely.
- disable approximate match
Reasoning: Only 1 result is returned with how it is currently used and being the correct result is important. Sometimes it matches against part of the string and that is not always desirable. Enabling it would be more for a feature to list objects with the name that contain the string.

default from_name to search for all authorities & disable approximate match

---

docs/api/crs/coordinate_operation.rst
pyproj/crs/coordinate_operation.py
test/crs/test_crs_coordinate_operation.py

Also, added in fix for scale factor in tests since it needs to be between 0-1.

ENH: Added EquidistantCylindricalConversion(and PlateCaree alias) and LambertCylindricalEqualAreaScaleConversion

---

pyproj/_crs.pyx

Based on: https://github.com/OSGeo/PROJ/pull/1899#discussion_r372905354
> for exotic geodetic CRS datum() might be NULL. You want to directly use geodeticCRS->ellipsoid() that will fetch the ellipsoid for the datumEnsemble() when datum() is NULL
This was originally modified in #509 as I thought the datum was never NULL, but that was incorrect.

revert getting ellipsoid/prime_meridian from datum

---

pyproj/crs/coordinate_operation.py
test/crs/test_crs_coordinate_operation.py

ENH: Use CRS to derive coordinate operation for LambertCylindricalEqualAreaScaleConversion in PROJ 7+

---

docs/api/crs/crs.rst
docs/history.rst
pyproj/crs/__init__.py
pyproj/crs/_cf1x8.py
pyproj/crs/coordinate_operation.py
pyproj/crs/crs.py
pyproj/crs/datum.py
test/crs/test_crs_cf.py
test/crs/test_crs_coordinate_operation.py
test/crs/test_crs_maker.py

ENH: Update from_cf/to_cf to use WKT instead of PROJ strings for internal management

---

pyproj/crs/coordinate_operation.py
test/crs/test_crs_coordinate_operation.py

Related to https://github.com/OSGeo/PROJ/issues/1930

Add warning for GeostationarySatelliteConversion where latitude_natural_origin is nonzero

---

pyproj/geod.py

This PR simply removes what looks like duplicated lines in 2 docstrings of the `pyproj.geod` module.
I've also noticed that three methods of the `Geod` class (namely `fwd`, `inv`, and `npts`) seem to be older than the other methods of the class, and don't have docstrings with properly formatted `Parameters` and `Returns` sections describing the function signatures.
I can update these docstrings if you want!

Remove duplicated lines from docstrings in geod.py

---

docs/history.rst
pyproj/crs/crs.py

BUG: Don't use CRS classes for defaults in CRS child class init signatures

---

docs/history.rst
pyproj/transformer.py
test/test_transformer.py

ENH: Added pyproj.transformer.Transform.__eq__()

---

pyproj/crs/crs.py
pyproj/proj.py
test/crs/test_crs.py
test/test_proj.py

Don't silently ignore kwargs when projparams are specified

---

docs/history.rst
pyproj/crs/crs.py
test/crs/test_crs_cf.py

This add the geographic_crs_name

BUG: Allow *_name to be added in CRS.to_cf

---

docs/history.rst
pyproj/__init__.py
pyproj/__main__.py
pyproj/_show_versions.py
test/crs/test_crs.py
test/crs/test_crs_cf.py
test/crs/test_crs_coordinate_operation.py
test/crs/test_crs_maker.py
test/test_awips221.py
test/test_datum.py
test/test_datum_shift.py
test/test_transform.py
test/test_transformer.py

I like `__proj_version__` as it stands out as something more of a version identifier.
It also is consistent with `rasterio.__gdal_version` and `fiona.__gdal_version__`.
I am not sure that it is a big enough change to warrant a minor version bump.

Added pyproj.__proj_version__

---

pyproj/crs/crs.py
test/crs/test_crs.py

See https://github.com/geopandas/geopandas/pull/1339#discussion_r407188802
Currently, you get
```
In [34]: CRS("epsg:4326") != 4326  
Out[34]: True
```
which should be False

BUG: fix unequal (!=) with non-CRS type

---

pyproj/_list.pyx
test/test_list.py

Add deprecation warnings for get_units_map and get_angular_units_map

---

pyproj/_transformer.pyx
pyproj/proj.py
pyproj/transformer.py
test/test_proj.py
test/test_transformer.py

Add warning for radians flag with Proj class

---

requirements-dev.txt
test/test_doctest_wrapper.py
test/test_geod.py

Since the start of 2020, Shapely 1.7.0 has binary wheels for Windows and Python 3.8, so some of the comments and logic used for testing is outdated. Furthermore, the test logic should only skip certain test if shapely is not installed in the test environment.

TST: Simplify logic if shapely is available, remove old comments

---

.pre-commit-config.yaml
.travis.yml
Makefile
docs/advanced_examples.rst
docs/conf.py
docs/examples.rst
docs/history.rst
docs/index.rst
pyproj/__init__.py
pyproj/__main__.py
pyproj/_crs.pyx
pyproj/_geod.pyx
pyproj/_proj.pyx
pyproj/_show_versions.py
pyproj/_transformer.pyx
pyproj/crs/coordinate_operation.py
pyproj/crs/crs.py
pyproj/enums.py
pyproj/exceptions.py
pyproj/geod.py
pyproj/proj.py
pyproj/transformer.py
setup.py
test/crs/test_crs.py
test/test_doctest_wrapper.py
test/test_proj.py
test/test_transformer.py

Drop support for python 3.5

---

.isort.cfg
docs/history.rst
pyproj/utils.py
requirements-dev.txt
test/test_utils.py

This includes at least:
- pandas.Series
- xarray.DataArray
- dask.array.Array

ENH: Support objects with __array__ method

---

docs/api/datadir.rst
docs/index.rst
docs/installation.rst
docs/transformation_grids.rst

DOC: Add transformation grid documentation page

---

pyproj/_datadir.pyx
test/conftest.py
test/crs/test_crs.py
test/test_datum.py
test/test_transformer.py

I thought this was done by default, but some tests revealed otherwise.

BUG: Make sure user directory in search paths

---

docs/history.rst
pyproj/_crs.pyx
test/crs/test_crs.py

Removed old `Datum.from_name` code that was only their for older versions of PROJ - no longer needed with PROJ >= 7.1 pin.
See: https://github.com/OSGeo/PROJ/issues/1823 & #631

ENH: Datum.from_name default to check all datum types

---

docs/history.rst
pyproj/_crs.pyx
test/crs/test_crs.py

ENH: Use from_user_input in __eq__ when comparing CRS sub-classes (ie. PrimeMeridian, Datum, Ellipsoid, etc.)

---

test/crs/test_crs.py
test/test_transformer.py

TST: Update tests with scope & remarks

---

pyproj/_crs.pyx
pyproj/_datadir.pxd
pyproj/base.pxi
pyproj/proj.pxi

- PJ_WKT2_2018 is deprecated: https://github.com/OSGeo/PROJ/blob/af8334a5c8f6ec7d98e7f7ce0564ed4684896426/src/proj.h#L772-L773
- ContextManager is from pyproj 2.3 single context implementation and no longer needed
- Changed external declarations to use `ctypedef` instead of `cdef`

CLN: PJ_WKT2_2018->PJ_WKT2_2019; remove ContextManager; ctypedef

---

docs/history.rst
pyproj/_crs.pyx
pyproj/proj.pxi

ENH: Use proj_is_equivalent_to_with_ctx in the place of proj_is_equivalent_to internally

---

docs/build_crs_cf.rst
pyproj/_crs.pyx
test/crs/test_crs_cf.py
test/crs/test_crs_coordinate_system.py

1. unit -> units
2. standard_name should be `latitude` & not geodetic latitude
3. The distinction of being depth or not will be managed by `direction` only. Changing `standard_name` as well is incorrect ([ref](http://cfconventions.org/cf-conventions/cf-conventions.html#vertical-coordinate))
4. Added `axis` for lon/lat "Optionally, the longitude type may be indicated additionally by providing the standard_name attribute with the value longitude, and/or the axis attribute with the value X."

BUG: CF to coordinate system fixes (unit-units;geodetic latitude;vertical direction)

---

pyproj/_datadir.pyx

I noticed core dumping and removed it and the dumping went away. I don't think they play nicely together.

CLN: Remove mypy typing from datadir cython code

---

setup.py

There are no tests for setup.py as far as I can tell I also think this does not need documentation.
This change should be "seamless" for pyproj but it will allow package parsers to inspect this by catching the BaseException instead of exiting.
Ping @marcelotrevisani who had issues in grayskull when parsing this package.

use SystemExit instead os sys.exit

---

pyproj/sync.py

Addresses this error from: https://travis-ci.com/github/pyproj4/pyproj-wheels/jobs/361979395
```
>       return codecs.ascii_decode(input, self.errors)[0]
E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 210: ordinal not in range(128)
```

BUG: Ensure geojson opened with encoding=utf-8

---

pyproj/geod.py
test/test_geod.py

Because `geod.geometry_area_perimeter` is signed, the handedness of the geometries coming in matters. There is an existing comment that says that counter-clockwise windings result in positive areas. The docs also point to the `shapely.geometry.polygon.orient` function which winds a polygon according to either the right-hand or left-hand rule. From the Shapely [docs](https://shapely.readthedocs.io/en/latest/manual.html#shapely.geometry.polygon.orient):
> A sign of 1.0 means that the coordinates of the product’s exterior ring will be oriented counter-clockwise and the interior rings (holes) will be oriented clockwise.
That means that if you are finding the area of a polygon wound using `orient`, the exterior would generate a positive area and the interiors (holes) would generate negative …

BUG: Fix handling of polygon holes when calculating area in Geod

---

.travis.yml
docs/advanced_examples.rst
docs/history.rst
pyproj/_datadir.pyx
test/test_datadir.py

Ran into a scenario where this may be useful when debugging the CA Bundle stuff with wheels.

ENH: Added support for debugging internal PROJ

---

.pre-commit-config.yaml
Makefile
setup.cfg
setup.py

Move static content from setup.py & flake8 options to setup.cfg

---

.isort.cfg
Makefile

https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/
```
Prior to version 5.0.0, isort wouldn't automatically traverse directories. The --recursive option was necessary to tell it to do so. In 5.0.0 directories are automatically traversed for all Python files, and as such this option is no longer necessary and should simply be removed.
```

LNT: Updates for isort 5

---

.travis.yml
appveyor.yml

CI: Update python pins - 3.7 is main version and add 3.9-dev

---

test/conftest.py

I think this will provide a more stable/consistent reset.

TST: Use the original PROJ network setting for rest in tests

---

requirements-dev.txt
test/test_cli.py
test/test_datadir.py
test/test_network.py
test/test_proj.py
test/test_sync.py
test/test_transformer.py

This PR replaces the external `mock` python package with `unittest.mock` from the standard library - and removes the requirement on `mock` external package.

Use unittest.mock from the standard library

---

appveyor.yml
ci/travis/proj-dl-and-compile
pyproj/_crs.pyx
pyproj/_datadir.pxd
pyproj/_datadir.pyx
pyproj/_network.pyx
pyproj/_sync.pyx
pyproj/_transformer.pyx
pyproj/database.pyx
pyproj/proj.pxi

Also connected to #661 and #675

REF: Use pyproj global context instead of the one from PROJ

---

docs/advanced_examples.rst
docs/build_crs.rst
docs/history.rst
docs/installation.rst
pyproj/_crs.pyx
pyproj/sync.py

The lintian QA tool reported several spelling errors for the Debian package build:
* Tranforming   -> Transforming
* accomodate    -> accommodate
* bulding       -> building
* contaning     -> containing
* exacly        -> exactly
* intialization -> initialization
* plaforms      -> platforms
* reguardless   -> regardless
* tranformation -> transformation
* ot            -> of

DOC: Fix spelling errors

---

.travis.yml
Makefile
docs/conf.py

@sebastic, you can build with:
```
cd docs/ && make man
```
and the file will be in `docs/_build/pyproj.1`
Mind trying it out?

DOC: Only include CLI page when building man pages 

---

pytest.ini
test/crs/test_crs.py
test/test_cli.py
test/test_datum.py
test/test_transformer.py

TST: Added grid and cli test markers

---

pyproj/geod.py

Specifies that the unit of the output for `Geod.line_length` and `Geod.line_lengths` is meters.

Specify units of measuring methods

---

docs/history.rst
pyproj/_transformer.pyx
pyproj/proj.pxi

Use proj_context_errno_string in PROJ 8+ due to deprecation

---

docs/history.rst
pyproj/_transformer.pyx
test/test_transformer.py

BUG: Allow transformations with empty arrays

---

requirements-docs.txt

3.5.0 released yesterday throwing errors [ref](https://github.com/pyproj4/pyproj/runs/1907433564?check_suite_focus=true)
```
Extension error (sphinx.ext.viewcode):
Handler <function env_purge_doc at 0x7fb608fe5700> for event 'env-purge-doc' threw an exception (exception: cannot unpack non-iterable bool object)
```

DOC: pin sphinx < 3.5.0

---

test/crs/test_crs_cf.py

TST: mask warning in test_cf_from_numpy_dtypes

---

.github/workflows/tests.yaml
appveyor.yml
docs/history.rst
docs/index.rst
pyproj/__init__.py
pyproject.toml
setup.cfg

DEP: Minimum supported Python version 3.7

---

docs/history.rst
pyproj/crs/crs.py
pyproj/transformer.py
test/crs/test_crs.py

REF: Multithread safe CRS

---

docs/history.rst
pyproj/_transformer.pyi
pyproj/_transformer.pyx
pyproj/transformer.py
test/test_transformer.py

ENH: Added authority,accuracy,allow_ballpark kwargs to Transformer.from_crs

---

docs/advanced_examples.rst
docs/history.rst
pyproj/_transformer.pyx
pyproj/base.pxi
pyproj/transformer.py
test/test_transformer.py

ENH: Add Transformer.transform_bounds

---

pyproj/_transformer.pyx
test/test_transformer.py

Discovered this when investigating https://github.com/OSGeo/PROJ/pull/2654
`proj_degree_input/output` and `proj_angular_output/output` all returned false.
Also, added return of input bounds when this occurs.

BUG: Skip noop transformations since they always return False for proj_degree_input

---

docs/advanced_examples.rst
docs/history.rst
pyproj/_transformer.pxd
pyproj/_transformer.pyi
pyproj/_transformer.pyx
pyproj/transformer.py
test/test_transformer.py

Skip equivalent/exact same is not needed. This means that one less CRS object is needed when re-creating `_Transformer` across threads.
```python
>>> from pyproj import CRS, Transformer
>>> crs = CRS(4326)
>>> tr = Transformer.from_crs(crs.to_proj4(), "+init=epsg:4326")
>>> tr.name
'noop'
>>> CRS(crs.to_proj4()) == "+init=epsg:4326"
True
>>> CRS(crs.to_proj4()).is_exact_same("+init=epsg:4326")
False
```

REF: Skip transformations if 'noop' & deprecate 'skip_equivalent'

---

docs/history.rst
pyproj/_geod.pxd
pyproj/_geod.pyx

Noticed this note and figured it was safe to update:
```
```

REF: Update pyproj.Geod.npts to use geod_inverseline

---

.all-contributorsrc
README.md
docs/api/enums.rst
docs/api/geod.rst
pyproj/_geod.pxd
pyproj/_geod.pyi
pyproj/_geod.pyx
pyproj/enums.py
pyproj/geod.py
test/test_geod.py

pyproj/geod.py - add a parameter `return_points` to Geod.npts() to determinate the return type; improve return type hint
pyproj/geod.py - add a parameters `initial_idx`, `terminus_idx` to Geod.npts()
pyproj/[geod.py, _geod.pyi, _geod.pyx] - add `inv_intermediate_by_npts` functions that uses given buffers `out_lons`, `out_lats` (and `out_azis`) buffers instead of creating new buffers
pyproj/_geod.pxd - add interface for `geod_lineinit`
pyproj/[geod.py, _geod.pyi, _geod.pyx] - add `inv_intermediate_by_del`, `fwd_intermediate_by_npts`, `fwd_intermediate_by_del` functions, similar to `inv_npts` but using forward calculation
test/test_geod.py - add tests for new functions
https://github.com/pyproj4/pyproj/pull/825/

add `[inv|fwd]_intermediate()` - to calculate intermediate points (like improved `Geod.npts()`)

---

.github/workflows/tests.yaml
requirements-dev.txt

From: https://github.com/pyproj4/pyproj/runs/2923083567
```
pyproj/network.py:8: error: Library stubs not installed for "certifi" (or incompatible with Python 3.9)
pyproj/network.py:8: note: Hint: "python3 -m pip install types-certifi"
pyproj/network.py:8: note: (or run "mypy --install-types" to install all missing stub packages)
pyproj/network.py:8: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
pyproj/network.py:57: error: Argument 1 to "_set_ca_bundle_path" has incompatible type "Union[Path, str, bool, None]"; expected "str"
```

DEP: Add types-certifi to dev requirements

---

docs/gotchas.rst
docs/history.rst

The answer now directly addresses the question, and also aligns with the
advice in the PROJ and geopandas documentation.
Fixes #789.

Update FAQ answer about CRS formats.

---

docs/api/crs/coordinate_operation.rst
docs/history.rst
pyproj/crs/_cf1x8.py
pyproj/crs/coordinate_operation.py
test/crs/test_crs_cf.py
test/crs/test_crs_coordinate_operation.py

BUG: Fix spelling for AzimuthalEquidistantConversion and LambertAzimuthalEqualAreaConversion

---

docs/history.rst
pyproj/_geod.pxd
setup.py

This reverts commit 6ef2d4fe971151bc48878319193e71fab86b3d36.
Based on what I have seen so far, this doesn't really provide much benefit due to the connection to the external PROJ. It also requires adding pyproj as a pre-build requirement. So, I think it would be better to wait on this until the benefits are more clear and more investigation has been completed.

Revert "ENH: Allow cimport (#870)"

---

docs/history.rst
pyproj/database.pyx
test/test_database.py

- Related to https://github.com/geopandas/geopandas/issues/2045

BUG: Make datum name match exact in query_utm_crs_info

---

docs/history.rst
pyproj/crs/crs.py
test/conftest.py
test/crs/test_crs.py
test/crs/test_crs_maker.py

BUG: Fix pickling for CRS builder classes

---

docs/history.rst
pyproj/_crs.pyx
pyproj/crs/crs.py
test/crs/test_crs.py
test/crs/test_crs_maker.py

Notes:
- The `from_*` methods were changed to bypass the `__init__` method. It also validates that it creates the expected type (Idea from https://github.com/pyproj4/pyproj/issues/847#issuecomment-843686871).
- The CRS properties were overridden to return a `CRS`. The reason for this is because the type of the CRS returned from that type is not guaranteed to always be the type of the original CRS.

REF: Make CRS methods inheritable

---

docs/history.rst
pyproj/crs/crs.py

Not going to deprecate this one as is should never have been there and isn't in the docstrings.

CLN: Remove ignore_axis_order from CRS.is_exact_same as it was added by accident

---

docs/history.rst
pyproj/utils.py

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html
> By default, astype always returns a newly allocated array. If this is set to false, and the dtype, order, and subok requirements are satisfied, the input array is returned instead of a copy.
Since `copy` is explicitly called beforehand, `copy=False` should be safe.

PERF: Disable unnecessary copy in dtype conversion for buffer

---

docs/history.rst
pyproj/utils.py

These have been phased out by numpy. 
- https://wiki.python.org/moin/NumArray
- https://en.wikipedia.org/wiki/NumPy#History

CLN: remove numeric/numarrays support

---

docs/api/crs/crs.rst
pyproj/crs/__init__.py
pyproj/crs/crs.py
test/crs/test_crs_maker.py

With the change in #902, the base class `CustomConstructorCRS` is useful for other libraries such as `cartopy` which have a different `__init__`:
- https://github.com/SciTools/cartopy/pull/1808#issuecomment-903305995
- https://github.com/SciTools/cartopy/pull/1808#issuecomment-903361329

REF: Rename _MakerCRS to CustomConstructorCRS and make public

---

pyproj/utils.py
test/test_transformer.py
test/test_utils.py

REF: use astype("d", order="C") instead of copy(order="C").astype("d")

---

docs/build_crs.rst
docs/crs_compatibility.rst
docs/history.rst
pyproj/_datadir.pyx
pyproj/_network.pyx
pyproj/datadir.py
pyproj/utils.py
requirements-test.txt
setup.py
test/conftest.py
test/crs/test_crs_cf.py
test/test_datadir.py

DEP: Remove distutils dependency

---

test/crs/test_crs.py

Resolving issue by adding this test and:
- https://github.com/OSGeo/PROJ/pull/2845
- https://github.com/conda-forge/sqlite-feedstock/pull/68
- https://github.com/pyproj4/pyproj-wheels/pull/37
- https://github.com/pyproj4/pyproj-wheels/pull/39

TST: Added test_crs_multiprocess

---

docs/history.rst
pyproj/_crs.pyx
test/crs/test_crs.py

BUG: Return multiple authorities with pyproj.crs.CRS.list_authority

---

docs/history.rst
pyproj/crs/_cf1x8.py
test/crs/test_crs_cf.py

BUG: CRS CF conversions ensure Pole rotation (netCDF CF convention) conversion works

---

pyproj/datadir.py

```
************* Module pyproj.datadir
pyproj/datadir.py:73:4: W0602: Using global for '_USER_PROJ_DATA' but no assignment is done (global-variable-not-assigned)
-----------------------------------
Your code has been rated at 9.99/10
```

LNT: address pylint complaint about _USER_PROJ_DATA

---

test/crs/test_crs.py

TST: skip test_crs_multiprocess for pypy

---

docs/history.rst
pyproj/_crs.pxd
pyproj/_crs.pyx
pyproj/crs/crs.py
test/crs/test_crs.py
test/crs/test_crs_maker.py

ENH: Prepend Derived to CRS type name if CRS is derived

---

docs/history.rst
pyproj/_transformer.pyx
test/test_transformer.py

version 3.2.1 results:
```
(inf, inf, -177.9054382738363, 71.43647664822007)
```

BUG: Improved handling of inf values in pyproj.transformer.Transformer.transform_bounds

---

docs/history.rst
pyproj/_transformer.pyx
pyproj/transformer.py
test/test_transformer.py

Script:
```python
from pyproj import CRS, Transformer
crs = CRS("EPSG:32661")
tr = Transformer.from_crs(crs, 4326, always_xy=True)
bounds = tr.transform_bounds(*crs.area_of_use.bounds, direction="INVERSE")
print(crs)
print(crs.area_of_use.bounds)
print(bounds)
print(tr.transform_bounds(*bounds))
crs = CRS("EPSG:32761")
tr = Transformer.from_crs(crs, 4326, always_xy=True)
bounds = tr.transform_bounds(*crs.area_of_use.bounds, direction="INVERSE")
print(crs)
print(crs.area_of_use.bounds)
print(bounds)
print(tr.transform_bounds(*bounds))
```
Current version (3.2.1)
```
EPSG:32661
(-180.0, 60.0, 180.0, 90.0)
(-1371213.7625429356, -1405880.71737131, 5371213.762542935, 5405880.71737131)
(-180.0, 48.65640565307887, 174.85815802748752, 60.292277663390834)
EPSG:32761
(-180.0, -90.0, 180.0, -60.0) …
```

ENH: Add support for transforming bounds at the poles

---

.github/workflows/tests.yaml

https://github.com/pyproj4/pyproj/runs/4057654052
Python 3.10 having issues with flake8 & cython for some reason.

CI: Use python 3.9 for lint checks

---

docs/examples.rst

Add a missing definition of ``cop`` to the getting started part of the
documentation.

Add missing definition of cop to docs

---

pyproj/crs/crs.py

According to the documentation for the `@abstractmethod` decorator:
> Using this decorator requires that the class's metaclass is
> ABCMeta or is derived from it.
(source: https://docs.python.org/3/library/abc.html#abc.abstractmethod)
Since `CustomConstructorCRS` and `CRS` are not defined as abstract
classes, using the `@abstractmethod` decorator does not actually do
anything and should be removed.

crs.py: remove @abstractmethod decorator

---

pyproj/_show_versions.py

Attempt based on suggestion: https://github.com/pandas-dev/pandas/issues/44980#issuecomment-1001237377

BUG: Reorder deps in show_versions for setuptools issue

---

appveyor.yml
docs/history.rst
pyproj/datadir.py
test/test_datadir.py

BUG: get_data_dir support for conda Windows enviroments

---

requirements-docs.txt

Latest jinja2 breaks docs build due to removal of deprecated features. Updated sphinx may help and previous issues requiring the pin are likely resolved.

DEP: Remove sphinx pin

---

.github/workflows/wheels.yaml
ci/proj-compile-wheels.sh

cibuildwheel seems to have become more official: https://github.com/pypa/cibuildwheel
Probably a good idea to migrate to using it as it will likely be better supported long-term. This is just the first step in that process.
Source for some ideas: https://github.com/pygeos/pygeos/blob/0835379a5bc534be63037696b1b70cf4337e3841/.github/workflows/release.yml
What this PR does:  adds X86_64 builds for OSX
This is helpful because the current wheels claim to be universal, but they are not.
Related:
- https://github.com/pyproj4/pyproj-wheels/issues/46
- https://github.com/pyproj4/pyproj-wheels/issues/42
- #1027

CI: Use cibuildwheel for OSX

---

docs/history.rst
pyproj/database.pyi

Tested with:
* Make an editable install of current PR code 
* Move to directory build in issue description and run `mypy` from there
```
(env) matthias@carbon:~/Sources/pyproj$ pushd ../../pyproj_issue/
~/pyproj_issue ~/Sources/pyproj
(env) matthias@carbon:~/pyproj_issue$ mypy test.py 
Success: no issues found in 1 source file
```

BUG: Complete database stub file with query_utm_crs_info() signature

---

docs/history.rst
docs/index.rst
docs/installation.rst

The default wheels for cibuildwheel are 2014, and that seems reasonable. This documents the change.

DOC: Add manylinux2014 notes

---

docs/history.rst
pyproj/crs/crs.py
test/crs/test_crs.py

Related to #1036
I wasn't able to find a real life scenario when this occurs. At this point it is purely theoretical. But, good to have a warning (and later an error) in case someone runs into it.

BUG: Warn when CRS cannot be converted to PROJ or PROJ JSON

---

docs/history.rst
pyproj/transformer.py
test/test_transformer.py

ENH: Added support to pickle Transformer

---

test/conftest.py
test/test_transformer.py

TST: Make tests PROJ 8.1+

---

.pylintrc
docs/history.rst
pyproj/_transformer.pyi
pyproj/_transformer.pyx
pyproj/proj.pxi
pyproj/transformer.py
test/test_transformer.py

ENH: Added authority, accuracy, and allow_ballpark kwargs to TransformerGroup

---

docs/history.rst
pyproj/crs/crs.py
pyproj/transformer.py
test/crs/test_crs_cf.py
test/test_transform.py
test/test_transformer.py

CLN: Remove deprecated 'skip_equivalent' kwarg from transformers and 'errcheck' kwarg from CRS.from_cf

---

test/conftest.py
test/crs/test_crs.py

TST: handle empty full_name in test_coordinate_operation_grids__alternative_grid_name with PROJ 9.1+

---

.github/workflows/tests.yaml

Related to: https://github.com/OSGeo/PROJ/issues/3192
Tests fail because the next release version of PROJ is not updated until the release.

CI: Remove latest PROJ docker build test

---

docs/history.rst
pyproj/crs/crs.py

`pyproj/crs/crs.py:595:17: C417 Unnecessary use of map - use a generator expression instead.`
Related: https://github.com/adamchainz/flake8-comprehensions/pull/409
Based on: https://github.com/rasterio/rasterio/pull/2352 (thanks @groutr :+1:)

REF: use regex to process PROJ strings in CRS.to_dict()

---

test/conftest.py
test/crs/test_crs.py

TST: test_coordinate_operation_grids__alternative_grid_name fixed to network full_name behavior

---

docs/history.rst
pyproj/crs/coordinate_operation.py
test/crs/test_crs_cf.py
test/crs/test_crs_coordinate_operation.py

Raises `CRSError` if latitude_natural_origin != 0.

BUG: Mercator A defined only for lat_0 = 0

---

.github/workflows/test_proj_latest.yaml
appveyor.yml
docs/history.rst
docs/installation.rst
pyproj/datadir.py
test/test_datadir.py

BUG: Add support for PROJ_DATA environment variable

---

docs/installation.rst

While reading through the installation docs I happened upon a minor typo, which is fixed in this PR.

DOC: Fix typo in installation docs

---

docs/history.rst
pyproj/utils.py
test/test_utils.py

As noted in #1102, projecting numpy masked arrays returned numpy masked
arrays in the 2.x series of pyproj.  This behaviour changed in commit
4ab3ff7 as part of the 3.x series, where a "plain" numpy ndarray was returned.  The change
implemented here ensures that projecting numpy masked arrays returns
masked arrays as was previously the case.
I'm fairly sure that the fix I've implemented here does actually fix the issue mentioned in #1102; nevertheless, please review my changes carefully as I'm not very familiar with this codebase.

BUG: Ensure numpy masked arrays stay masked after projection

---

test/test_transformer.py

Not really a big fan of this as it makes the test useless for PROJ 9.1+. Maybe adding #1071 will help?

TST: Update test_transformer*__area_of_interest for PROJ 9.1

---

setup.py

runtime_library_dirs isn't supported by PE/COFF, used by Windows and Cygwin; it seems to be an ELF thing.

BLD: Don't specify runtime_library_dirs on Cygwin

---

docs/history.rst
pyproj/_transformer.pyi
pyproj/_transformer.pyx
pyproj/transformer.py
test/conftest.py
test/test_transformer.py

ENH: Added force_over kwarg to Transformer.from_crs

---

docs/history.rst
setup.py

BUG: Fix finding PROJ version with PROJ_LIB and PROJ 9.1+

---

test/crs/test_crs.py

Related: #1080 #1090
https://github.com/pyproj4/pyproj/runs/8198324186
```
@pytest.mark.grid
def test_coordinate_operation_grids__alternative_grid_name():
...
if PROJ_GTE_91 and pyproj.network.is_network_enabled():
assert grid.available is True
>           assert grid.full_name == ""
E           AssertionError: assert '/home/runner..._ntv1_can.tif' == ''
E             + /home/runner/.local/share/proj/ca_nrc_nt
```

TST: test_coordinate_operation_grids__alternative_grid_name - handle when PROJ 9.1 and local grid exists

---

pyproj/_show_versions.py

This should simplify the logic and be more robust.

REF: Use importlib.metadata.version in show_versions for python deps

---

docs/advanced_examples.rst
docs/examples.rst
docs/gotchas.rst
docs/history.rst
pyproj/_crs.pyx
pyproj/crs/crs.py
pyproj/proj.py
pyproj/transformer.py

The EPSG database uses the uppercase version. This is for consistency with `to_authority`.

REF: Use upper case EPSG code when creating CRS

---

docs/history.rst
pyproj/crs/crs.py
test/crs/test_crs_cf.py

Related: https://github.com/corteva/rioxarray/discussions/591

BUG: Fix CRS.to_cf for Pole rotation GRIB convention

---

.github/workflows/release.yaml

This PR extends the GitHub workflow build matrix to include one more item with variables `{os: "windows-2019": arch: "auto32", triplet: "x86-windows"}`, similarly to the already present win64 build. 
- No new tests, but I checked that the current tests pass on win32 (as run by cibuildwheel).
- I have not updated `history.rst` because I was not sure if this addition was that relevant (wheels were already there in `pyproj` 3.3.1, so this PR simply brings them back).

WHL: Add win32 to build_wheels matrix

---

docs/history.rst
pyproj/_crs.pyx

List elements were not properly disposed of when iterating the results of proj_identify. This fixes this and simplifies the cleanup logic.
You can reproduce this issue with the following snippet (look at the memory usage):
```python
from pyproj import CRS
for i in range(10000):
CRS.from_epsg(3857).to_epsg()
```

BUG: Fix memory leak in CRS.list_authority

---

.github/workflows/test_proj_latest.yaml
.github/workflows/tests.yaml

CI: Add Network + Global Context test

---

pyproj/transformer.py

Related #1161
Documentation only change so it is more obvious that you should prefer `from_crs` and `from_proj` may be removed in the future. If it is going to be removed, warnings will be added later.

MNT: Soft-deprecate Transformer.from_proj

---

pyproj/geod.py
test/test_geod.py

This adds the ability to reuse the arrays passed in and out of the geod functions, following the same idea as the Transformers. I noticed this while profiling some of Cartopy's code and we could potentially get some speedup over there from this. We spend a lot of time in `_copytobuffer`.
I'm not sure if you would want the inplace applied to all potential inputs (i.e. `ind` as well) or just the outputs. Seems best to make it all to avoid the copy if possible.

ENH: Add inplace kwarg to Geod.fwd and Geod.inv

---

pyproj/_transformer.pyx

Currently, `Enum.create()` adds quite a bit of overhead to the transform calls, so we probably don't want to call it when unnecessary. Here I added `isinstance()` checks to handle it in a completely backwards compatible way.
```python
In [1]: from pyproj import Transformer
In [2]: transformer = Transformer.from_crs(2263, 4326, always_xy=True)
In [3]: %timeit transformer.transform(1, 2, direction="forward")
7.96 µs ± 32 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
In [4]: %timeit transformer.transform(1, 2, direction="FORWARD")
4.18 µs ± 33.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
In [5]: %timeit transformer.transform(1, 2)
3.26 µs ± 21.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
I think it might be even nicer to remove …

PERF: Faster transform direction if already passed an Enum

---

pyproj/_transformer.pyx

Related: #1205
@greglucas, this seems to be consistently faster for some reason. Can you verify?

PERF: Use isinstance in get_pj_direction

---

pyproj/transformer.py
test/conftest.py
test/test_transform.py

TST: move tests using NADCON grids to test_transform

---

.pylintrc
docs/history.rst
pyproj/_transformer.pyi
pyproj/_transformer.pyx
pyproj/proj.pxi
pyproj/transformer.py
test/conftest.py
test/test_transformer.py

Related: #1202
```python
In [1]: from pyproj import Transformer
In [2]: transformer = Transformer.from_crs(4326, 3857, always_xy=True)
In [3]: %timeit transformer.transform(1, 2)
4.69 µs ± 37.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
In [4]: %timeit transformer.transform_point(1, 2)
2.08 µs ± 20.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
Version in #1203:
```python
In [5]: %timeit transformer.transform_point(1, 2)
2.99 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

PERF: Optimize point transformations

---

pyproj/_geod.pyi
pyproj/_geod.pyx
pyproj/geod.py
test/test_geod.py

This adds a fast-path for scalar inputs by trying out a double-only implementation, and falling back if any input is not a double. An alternative is to add `Geod.fwd_point()` and `Geod.inv_point()` functions as well, but I kind of like this transparent form for simplicity of users only needing one function and only a minor overhead for arrays where you are already going through some slower paths.
A little under 10x improvement for scalars.
```python
In [1]: from pyproj import Geod
In [2]: g = Geod(ellps="WGS84")
In [3]: %timeit g.fwd([0], [0], [1], [1])
4.76 µs ± 28.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
In [4]: %timeit g.fwd(0, 0, 1, 1)
588 ns ± 4.57 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

PERF: Optimize for single point in Geod fwd/inv functions

---

test/test_transform.py

TST: update nad83 to nad27 tests for grids

---

pyproj/exceptions.py
pyproj/transformer.py

This shouldn't have been a public method - an oversight. Removing as no longer needed.

CLN: Remove clear method from pyproj exceptions

---

test/test_geod.py

This converts the really big test into smaller tests to make the code clearer and easier to debug. This also removes the interdependence on subsections of the tests.

TST:geod: Separate geodesic tests for clarity

---

docs/history.rst
pyproj/crs/crs.py
test/crs/test_crs.py

REF: Raise error when CRS.to_wkt, CRS.to_json, or CRS.to_proj4 returns None

---

docs/history.rst
pyproj/crs/coordinate_operation.py
test/crs/test_crs_coordinate_operation.py

Related: #882
AzimuthalEquidistantConversion & LambertAzimuthalEqualAreaConversion should be used instead.

CLN: Remove AzumuthalEquidistantConversion & LambertAzumuthalEqualAreaConversion

---

.github/workflows/tests.yaml

Related: https://github.com/conda-forge/pyproj-feedstock/pull/129

CI: Remove PROJ pin in conda tests

---

docs/history.rst
pyproj/_transformer.pyi
pyproj/_transformer.pyx
pyproj/proj.pxi
pyproj/transformer.py
test/test_transformer.py

ENH: Added `allow_superseded` kwargs to `TransformerGroup`

---

.github/workflows/tests.yaml
appveyor.yml
docs/history.rst
docs/index.rst
pyproj/__init__.py
setup.cfg

DEP: Minimum supported Python version 3.9

---

ci/proj-compile-wheels.sh

- Okay to use SQLite 3.42: https://github.com/OSGeo/PROJ/issues/3629

WHL: Update sqlite,libtiff,curl,nghttp2

---

docs/history.rst
pyproj/_geod.pyi
pyproj/_geod.pyx
pyproj/geod.py
test/test_geod.py

BUG: fix Geod.npts NaN handling

---

docs/history.rst

I think that this is missing from: https://github.com/pyproj4/pyproj/pull/1206

DOC: Add a reference to #1206 in history

---

docs/advanced_examples.rst

Hello there👋
I have made a pull request to fix a small typo in the documentation.

DOC: fixed typo 'create create' -> 'create'

---

README.md

Fixe to allow for the logo to be visible on the top of the README.md in [Pypi](https://pypi.org/project/pyproj/) by referencing the logo directly, not relative references

Fix logo view on Pypi

---

pyproj/_geod.pyx
pyproj/geod.py

DOC: Spelling permimeter -> perimeter

---

docs/history.rst
pyproj/_datadir.pxd
pyproj/_datadir.pyx
pyproject.toml

BUG: Cython 3 compatibility fixes

---

.github/workflows/release.yaml
.github/workflows/test_proj_latest.yaml
.github/workflows/tests.yaml
pyproject.toml
requirements-test.txt

DEP: Add Python 3.12 support

---

.cirrus.yml
.github/workflows/release.yaml

CI: Update cibuildwheel v0.16

---

pyproj/_transformer.pyx
pyproj/database.pyx

These calls can take hundreds of milliseconds to access the PROJ databases, during which time no other Python code in any other thread can run. Use `nogil` to avoid this effect.
This should be safe for these calls as they all take a separate PROJ threading context.
It's quite probable there are other calls which could use this, but these negatively affected my application and I was able to identify them. I would welcome additions to the set of calls to wrap.

PERF: drop GIL during long-running proj database calls

---

.github/workflows/build_docs.yaml
.github/workflows/test_proj_latest.yaml
.github/workflows/tests.yaml
appveyor.yml
docs/history.rst
docs/index.rst
pyproj/__init__.py
pyproject.toml

Python 3.9 is no longer supported in the scientific python ecosystem: https://scientific-python.org/specs/spec-0000/
Related #1111

DEP: Minimum supported Python version 3.10

---

pyproj/crs/_cf1x8.py

Related: https://github.com/OSGeo/PROJ/pull/3988
```
_________________________ test_azimuthal_equidistant __________________________
def test_azimuthal_equidistant():
crs = CRS("ESRI:54032")
expected_cf = {
"semi_major_axis": 6378137.0,
"semi_minor_axis": crs.ellipsoid.semi_minor_metre,
"inverse_flattening": crs.ellipsoid.inverse_flattening,
"reference_ellipsoid_name": "WGS 84",
"longitude_of_prime_meridian": 0.0,
"prime_meridian_name": "Greenwich",
"geographic_crs_name": "WGS 84",
"horizontal_datum_name": "World Geodetic System 1984",
"projected_crs_name": "World_Azimuthal_Equidistant",
"grid_mapping_name": "azimuthal_equidistant",
"latitude_of_projection_origin": 0.0,
"longitude_of_projection_origin": 0.0,
"false_easting": 0.0,
"false_northing": 0.0,
}
cf_dict = crs.to_cf()
assert …
```

BUG: Support azimuthal_equidistant coordinate operation to CF

---

.pre-commit-config.yaml
HOW_TO_RELEASE.md
docs/history.rst
pyproj/crs/coordinate_operation.py
pyproj/crs/crs.py

Adds [`codespell`](https://github.com/codespell-project/codespell) to pre-commit hooks to catch common misspellings. Includes fixes for a few existing misspellings in repo
```
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
black....................................................................Passed
isort....................................................................Passed
blacken-docs.............................................................Passed
flake8...................................................................Passed
flake8-pyx...................................................... …
```

Adds codespell to pre-commit hooks

---

test/crs/test_crs.py

Make test for datum wkt more flexible for a datum ensemble. New members can be added, as in PROJ 9.4.1.

Test datum ensemble allowing new members

---

.github/workflows/release.yaml

- https://github.com/actions/runner-images
- https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/

CI: Macos 11 -> Macos 12

---

pyproj/_context.pyx

```
warning: pyproj/_context.pyx:110:95: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
```

BUG: Address cython nogil signature warning

---

docs/history.rst
pyproj/crs/_cf1x8.py
pyproj/crs/coordinate_operation.py
test/conftest.py
test/crs/test_crs_coordinate_operation.py

BUG: Handle changes to HotineObliqueMercatorBConversion

---

docs/crs_compatibility.rst

Change title to correct one, was saying cartopy when that was the previous section.

Update crs_compatibility.rst to fix a title

---

.github/workflows/release.yaml

xref: https://github.com/adang1345/delvewheel/issues/54
Additionally, vcpkg has a download error when running with a bash shell so we need to add some extra exports as a workaround. https://github.com/microsoft/vcpkg/issues/41199#issuecomment-2378255699
- [n/a] Tests added

BLD: Add Windows system path to delvewheel add-path

---

.pylintrc

pylint 3.3.0 added a new rule that is causing failures. There is already an ignore rule for too many arguments, so also add the ignore rule for the positional specific arguments.

MNT: Add too-many-positional-arguments to lint ignore rules

---

.github/workflows/tests.yaml

Looks like micromamba v2 release doesn't work on GitHub Actions runners currently, so pin the version back.
xref: https://github.com/mamba-org/setup-micromamba/issues/225

CI: Pin micromamba due to CI Runner incompatibilities with newer versions

---

.github/workflows/test_proj_latest.yaml
pyproj/_crs.pyx
pyproj/_geod.pyx
pyproj/_transformer.pyx
pyproj/database.pyx
test/test_proj.py

This fixes the errors that came up during Cython3.1a testing. I'm not a Cython expert by any means, so let me know if there is a better way to handle any of these. Do you want to add a test/workflow for upcoming Cython releases?
Test with this nightly wheel release install locally:
```
pip install --upgrade --pre --only-binary :all: -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple cython numpy
pip install .
python -m pytest
```

Cython 3.1+ fixes

---

test/test_proj.py

TST: remove checking is python >= 3.4

---

pyproj/crs/coordinate_operation.py
pyproj/crs/crs.py
pyproj/geod.py
pyproject.toml

I strengthen the `mypy` and `ruff` config a bit to disallow `type: ignore` with no code, found one case when the ignore can be removed

Disallow type error without code

---

.github/workflows/release.yaml
ci/proj-compile-wheels.sh

I wasn't sure if I could safely run github CI on my fork, so there might be some issues that I missed.
I did test these changes locally though using a local installation of `cibuildwheel` and this script:
```bash
#!/usr/bin/env bash
export CIBW_SKIP="pp*-win* pp31*"
export CIBW_ARCHS="x86_64"
export CIBW_ENVIRONMENT_LINUX="PROJ_WHEEL=true PROJ_NETWORK=ON PROJ_VERSION=9.5.0 PROJ_DIR=/project/pyproj/proj_dir"
export CIBW_BEFORE_ALL_LINUX="bash ./ci/proj-compile-wheels.sh"
export CIBW_TEST_REQUIRES="cython pytest numpy --config-settings=setup-args=\"-Dallow-noblas=true\""
export CIBW_BEFORE_TEST="python -m pip install shapely pandas xarray || echo \"Optional requirements install failed \""
export CIBW_TEST_COMMAND="pyproj -v && python -c \"import pyproj; pyproj.Proj(init='epsg:4269')\" && cp …
```

CI: Add wheels for musllinux (closes #1382)

---

.github/workflows/release.yaml
docs/history.rst

- https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/
- https://github.com/actions/runner-images/issues/10721

CI: Update to macos 13 runner & add linux arm runner

---

pyproj/geod.py

DOC: update doc geometry_area_perimeter

---

pyproj/_crs.pyx
pyproj/crs/crs.py

These comments are visible in the API docs: https://pyproj4.github.io/pyproj/stable/api/crs/crs.html
The correct way to handle long lines in a docstring is to put the ignore at the end of the docstring.

DOC: Remove 'noqa: E501' from docstrings

---

pyproj/crs/__init__.py

This PR explicitly exports all classes in `pyproj.crs`, allowing type checkers like mypy to better use the type hints. Without this change, mypy will complain with an error like:
```console
> mypy --strict foo.py
foo.py:3: error: Module "pyproj.crs" does not explicitly export attribute "CRS"  [attr-defined]
```

pyproj.crs: add imports to __all__

---

.isort.cfg
.pre-commit-config.yaml
.stickler.yml
CONTRIBUTING.md
README.md
pyproj/__init__.py
pyproj/crs/__init__.py
pyproj/geod.py
pyproj/transformer.py
pyproject.toml
requirements-dev.txt
test/test_doctest_wrapper.py
test/test_transformer.py

This maintenance PR does the following:
- Replace Black with the Ruff formatter
- Replace isort with Ruff's "I" lint check
- Update the Ruff version in pre-commit, which changes a few source files
- Remove target-version from ruff configuration, since this is automatically evaluated
- Add ruff to requirements-dev.txt
- Update relevant excerpts of CONTRIBUTING.md with these changes

MNT: replace black and isort with ruff format and lint

---

docs/history.rst
test/test_transformer.py

@snowman2 I'm not sure if this is what you mean, but I understood your last comment to mean that updating this pyproj test for PROJ 9.6.2 would result in not actually testing anything in pyproj since all the values are now valid. So in this PR I've removed the test.
Release this as an rc1?

TST: Remove irrelevant test with modern PROJ versions
