- .gitignore
- setup.py
Windows compilation fix, error checking and a .gitignore.
> Minor improvements

- lib/pyproj/__init__.py
(https://github.com/matplotlib/basemap/pull/212)
> port of basemap fix for input arrays in fortran order

- README.md
- unittest/test.py
1. Added new unit test for PR #23 .
2. Small patch to make unit test for PR #20 work.
3. Added line about running new unit tests in README.md.
> Unit test fix, new unit test, added running unit tests to README

- lib/pyproj/__init__.py
PR #30 forgot to `import sys`.
> Import sys

- .travis.yml
Runs the unittest/test.py in Travis.
> run unittests in Travis

- README.md
Added header sections.  The header sections are to make it look similar to other projects on github.   Also, tried to improve the installation section.  Hopefully, I did not change any of the facts of how installation is suppose to occur.
> Improved README.md.

- _proj.pyx
- lib/pyproj/__init__.py
Attempt to expose pj_get_def to user (related to #77). Input appreciated. 
Also, not clear to me how "tests" work in this library -- no unit testing with assert statements? Just print outputs for user to look for errors?
> Initial commit of exposing pj_get_def

- _proj.pyx
- unittest/test.py
This pull request addresses issue #84.
I've created a new unittest class to test the Geod methods, and will shortly push changes to fix the issue.
Regards,
Chris.
> Radians fix

- _proj.pyx
- unittest/test.py
> Fix set_datapath to allow unicode paths to be decoded into bytes.

- .travis.yml
- requirements-dev.txt
> Add Python 3.7 to Travis

- .travis.yml
- requirements-dev.txt
Not sure if this works or not. Would need to activate coveralls.io to test.
> use coverage reporting for coveralls.io

- pyproj/__init__.py
- pyproj/_proj.pyx
- sphinx/history.rst
> support for unit conversion to/from radians for transform/itransform

- .travis.yml
- pyproj/_transformer.pxd
- pyproj/_transformer.pyx
- pyproj/transformer.py
- sphinx/history.rst
- unittest/test_transformer.py
Attempt for #192 & #195 - needs work.
> fixed logic for converting between radians/degrees for transformations

- pyproj/_crs.pyx
- pyproj/_proj.pyx
- pyproj/_transformer.pxd
- pyproj/_transformer.pyx
- pyproj/transformer.py
- sphinx/index.rst
- sphinx/optimize_transformations.rst
- unittest/test.py
- unittest/test_transformer.py
> skip tranformation operation if input and output projections are equivalent

- appveyor.yml
- pyproj/_crs.pyx
- pyproj/_datadir.pxd
- pyproj/_datadir.pyx
- pyproj/_proj.pyx
- pyproj/_transformer.pyx
- pyproj/datadir.py
- setup.py
- sphinx/api/datadir.rst
- sphinx/installation.rst
- unittest/test_datadir.py
- look in PATH for data directory #176
- support multiple data directories #199
- use functions in setup.py to logically divide functionality (from old windows wheel attempts that were lost)
> Update data directory functionality

- pyproj/_datadir.pxd
- pyproj/_datadir.pyx
- pyproj/exceptions.py
- pyproj/proj.pxi
- unittest/test_exception_logging.py
> add proj error message to exceptions

- test/geodtest.py
- test/test.py
- test/test2.py
Replace:
cPickle with pickle
commands.getoutput() with subprocess.check_output()
All also run on Python 2.7.
> make tests in /test Python 3 compatible

- pyproj/transformer.py
- sphinx/api/transformer.rst
> Added axis order warning in transformer docs

- pyproj/_datadir.pyx
- pyproj/datadir.py
- test/test_datadir.py
Fix based on: https://proj4.org/usage/environmentvars.html
> fix data dir path separator to be (;) for windows and (:) for linux

- test/test_datum_shift.py
> updated gauss datum shift test EPSG from 26592 (deprecated) to 3004

- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/test_exception_logging.py
- test/test_transformer.py
> fix error count for transformations; fix from_crs deprecation warning

- pyproj/_crs.pyx
- test/test_crs.py
> added check in to_epsg for when proj_list is null

- pyproj/_crs.pyx
- test/test_crs.py
> added option to pretty print CRS.to_wkt

- pyproj/crs.py
- pyproj/proj.py
- test/test_proj.py
> fixed initialization from non DerivedGeographicCRS (fixes #270)

- setup.py
Also fixes a warning:
```
/usr/lib/python3.7/distutils/extension.py:131: UserWarning: Unknown Extension options: 'embedsignature'
```
and gets introspection working in ipython. It does fill in missing annotations in html docs when you rebuild them, but the way Cython does it isn't always ideal e.g. including `self` in class method signatures.
```diff
--- a/docs/html/api/crs.html
+++ b/docs/html/api/crs.html
@@ -218,7 +218,7 @@ about specifying projection parameters.</p>
<dl class="method">
<dt id="pyproj.crs.CRS.is_exact_same">
-<code class="descname">is_exact_same</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.is_exact_same" title="Permalink to this definition">¶</a></dt>
+<code class="descname">is_exact_same</code><span …
```
> embedsignature is a Cython compiler directive

- pyproj/_proj.pxd
- pyproj/_transformer.pxd
- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/test_transformer.py
> undo deprecation of Transformer.from_crs &  added direction to Transformer

- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/crs.py
- test/test_crs.py
Beginning to address: https://github.com/pyproj4/pyproj/issues/264#issuecomment-484686605
> update CRS repr to support compound CRS, use CRS name, etc

- docs/api/index.rst
- pyproj/_crs.pyx
- pyproj/_transformer.pyx
- pyproj/enums.py
- pyproj/transformer.py
- setup.py
- test/test_crs.py
- test/test_transformer.py
> added enumeration objects for pyproj

- docs/installation.rst
- Linking to Gohlke's wheels is no longer necessary, as those are now uploaded to PyPI as well?
- added some links
> DOC: update installation notes

- .travis.yml
- appveyor.yml
- docs/api/transformer.rst
- docs/index.rst
- pyproj/_transformer.pyx
- pyproj/proj.pxi
- pyproj/transformer.py
- setup.py
- test/test_transformer.py
> added always_xy option to transformer & minumum PROJ version to 6.1.0

- pyproj/_crs.pyx
- pyproj/_transformer.pyx
- pyproj/enums.py
- test/test_crs.py
- test/test_transformer.py
Addresses #298 and https://github.com/pyproj4/pyproj/pull/288#issuecomment-490122764
Uses idea from https://github.com/pyproj4/pyproj/pull/288#issuecomment-490123157 to better handle invalid input.
@jorisvandenbossche
> made TransformDirection enum string based; added _missing_ method to raise error when value missing

- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/proj.py
- test/test_crs.py
> add CRS.geodetic_crs as replacement for CRS.to_geodetic()

- appveyor.yml
- pyproj/_crs.pyx
- pyproj/_transformer.pyx
- pyproj/enums.py
- setup.py
- test/test_crs.py
- test/test_transformer.py
Closes #301
@jorisvandenbossche
> made enumeration lookup case insensitive

- pyproj/_crs.pyx
- pyproj/crs.py
- test/test_crs.py
> deprecate CRS.is_valid

- pyproj/crs.py
- test/test_crs.py
> made CRS hashable

- pyproj/_crs.pyx
- pyproj/crs.py
- pyproj/proj.py
- test/test_crs.py
- test/test_crs_cf.py
- test/test_proj.py
> allow for creation of CRS from user input in init

- pyproj/_crs.pyx
- pyproj/_proj.pyx
- test/test_crs.py
- test/test_proj.py
> add support for comparing Proj & CRS objects to different types

- pyproj/crs.py
- test/test_crs.py
> allow comparing CRS with a non-CRS type supported by CRS.from_user_input

- pyproj/_crs.pyx
- test/test_crs.py
closes #314 
closes #316
closes #317
> fix is_geocentric for bound crs & add is_vertical, is_engineering to CRS

- docs/api/index.rst
- docs/api/proj.rst
- docs/api/transformer.rst
- docs/examples.rst
- docs/index.rst
- pyproj/proj.py
>  added getting started guide to documentation 

- docs/history.rst
- pyproj/_crs.pyx
- pyproj/_transformer.pxd
- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/test_transformer.py
Closes #321 
- Add check for valid initialization of Transformer
- Add check to ensure PJ* is transfomation
- Add to_wkt
- Add PJ_PROJ_INFO attributes
> Transformer refactor/additions

- docs/api/index.rst
- docs/history.rst
- pyproj/__init__.py
- pyproj/_show_versions.py
- test/test_show_versions.py
> added pyproj.show_versions() for debugging

- .gitignore
- .travis.yml
- Makefile
- README.md
- appveyor.yml
- create_docs.sh
- docs/installation.rst
- pyproj/__init__.py
- pyproj/_show_versions.py
- pyproj/compat.py
- pyproj/crs.py
- pyproj/enums.py
- pyproj/geod.py
- pyproj/proj.py
- pyproj/transformer.py
- pyproj/utils.py
- requirements-dev.txt
- setup.py
- test/test_awips221.py
- test/test_crs.py
- test/test_datadir.py
- test/test_datum_shift.py
- test/test_exception_logging.py
- test/test_pickle.py
- test/test_show_versions.py
> added Makefile and updated code to pass 'make check'

- setup.py
> remove brackets and try/except from subprocess call for proj version

- docs/history.rst
- pyproj/crs.py
- test/test_crs.py
> remove whitespace between equals and PROJ params in PROJ string

- Makefile
- docs/examples.rst
- docs/history.rst
- pyproj/_geod.pxd
- pyproj/_geod.pyx
- pyproj/crs.py
- pyproj/geod.py
- requirements-dev.txt
- test/test_doctest_wrapper.py
- test/test_geod.py
> Geodesic: Added polygon area computations & support for shapely geometries

- docs/history.rst
- pyproj/_crs.pyx
- pyproj/_proj.pyx
- pyproj/crs.py
- pyproj/proj.py
- test/test_crs.py
- test/test_datum_shift.py
- test/test_proj.py
- test/test_transformer.py
> make +init= deprecaton a FutureWarning; remove deprecated functionality

- docs/examples.rst
- docs/history.rst
- pyproj/_transformer.pyx
- pyproj/proj.pxi
- pyproj/transformer.py
- test/test_transformer.py
> Added Transformer.operations and added missing definition for cases when it is unknown

- docs/api/transformer.rst
- docs/examples.rst
- docs/history.rst
- pyproj/_transformer.pxd
- pyproj/_transformer.pyx
- pyproj/proj.pxi
- pyproj/transformer.py
- test/test_transformer.py
> Added pyproj.transformer.TransformerGroup to make all transformations available

- docs/api/transformer.rst
- docs/examples.rst
- docs/history.rst
- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/_transformer.pxd
- pyproj/_transformer.pyx
- pyproj/proj.pxi
- pyproj/transformer.py
- test/test_transformer.py
Also added area_of_use to Transformer and CoordinateOperation
> added area_of_interest for pyproj transformers using CRS to initialize

- docs/history.rst
- docs/installation.rst
- pyproj/datadir.py
- pyproj/transformer.py
- setup.py
- test/test_datadir.py
- test/test_transformer.py
> search on sys.prefix for the PROJ data directory

- pyproj/__init__.py
> bump version to 2.3.0

- test/test_datadir.py
> use mock for changing os.environ and sys.prefix in data directory tests

- pyproj/geod.py
- test/test_geod.py
> reduce precision constrants on geodesic tests

- pyproj/_crs.pyx
- pyproj/_transformer.pyx
Addresses https://github.com/pyproj4/pyproj/pull/412#discussion_r324126146
> remove initialize_context method as not good to have publicly available

- pyproj/_crs.pyx
- pyproj/_show_versions.py
- pyproj/_transformer.pyx
- pyproj/crs.py
- pyproj/geod.py
- pyproj/transformer.py
> start adding versionadded

- docs/history.rst
- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/_transformer.pxd
- pyproj/_transformer.pyx
- pyproj/proj.pxi
- pyproj/transformer.py
- test/test_crs.py
- test/test_transformer.py
> Scope, Remarks, Operations

- docs/api/enums.rst
- docs/api/list.rst
- docs/history.rst
- pyproj/__init__.py
- pyproj/_list.pyx
- pyproj/enums.py
- pyproj/proj.pxi
- test/test_list.py
> Added pyproj.get_authorities() and pyproj.get_codes()

- docs/history.rst
- pyproj/_geod.pxd
- pyproj/_geod.pyx
- pyproj/_proj.pyx
- pyproj/_transformer.pyx
- pyproj/base.pxi
- pyproj/proj.pxi
@jorisvandenbossche mind trying this out?
> release gil in core cython/PROJ code

- pyproj/_proj.pyx
Addresses https://github.com/pyproj4/pyproj/pull/437#issuecomment-532093283
Related to: #386
> fix releasing gil in pyproj.Proj code

- HOW_TO_RELEASE.md
> add how to release

- test/test_transformer.py
> add aoi_data_directory fixture to stabilize tests with area of interest

- docs/api/enums.rst
- docs/index.rst
- docs/past_versions.rst
> added links to past versions of the documentation

- test/test__main__.py
> update to use sys.executable for test in main

- test/test__main__.py
> added tmp_chdir context manger for tests in main to prevent conflicts

- pyproj/datadir.py
> Fix typo in datadir docs: rhe -> the

- docs/history.rst
- pyproj/cf1x8.py
- pyproj/crs.py
- test/test_crs_cf.py
> Fix setting lat_ts for mercator projection in CRS.from_cf() and CRS.to_cf()

- docs/advanced_examples.rst
- docs/examples.rst
- docs/history.rst
- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/crs.py
- pyproj/transformer.py
- test/test_crs.py
> Add repr for pyproj.crs.CoordinateOperation and for pyproj.transformer.TransformerGroup

- test/test_crs.py
- test/test_crs_cf.py
> fix +proj=ob_tran +o_proj=longlat CRS tests for PROJ > 6.2.0

- .travis.yml
> add python 3.8 to build matrix

- docs/history.rst
- pyproj/crs.py
- test/test_crs_cf.py
Related: https://github.com/OSGeo/PROJ/issues/1601#issuecomment-531055850
> latlon -> longlat for from_cf for o_proj

- pyproj/crs.py
- test/conftest.py
- test/test_datum.py
- test/test_doctest_wrapper.py
- test/test_transformer.py
Addresses https://github.com/pyproj4/pyproj/issues/474#issuecomment-550390971
ping @cgohlke
> Add aoi_data_directory fixture to additional tests where the ntv2.0.gsb file can cause tests to fail

- docs/installation.rst
- setup.py
> added instructions for installing manylinux2010 wheels

- docs/history.rst
- pyproj/_crs.pyx
- pyproj/crs.py
- pyproj/proj.py
- test/test_crs.py
- test/test_crs_cf.py
- test/test_datum_shift.py
- test/test_doctest_wrapper.py
- test/test_proj.py
- test/test_transformer.py
cc: @jorisvandenbossche @djhoese
> elevate +init= warning to FutureWarning; add UserWarning to CRS.to_proj4()

- docs/history.rst
- pyproj/_proj.pyx
- pyproj/base.pxi
- pyproj/proj.py
- This should make the output consistent with the `Transformer`
- Also, use HUGE_VAL to initialize PJ_COORD instead of float('inf')
> return HUGE_VAL in Proj instead of 1.e30

- docs/history.rst
- pyproj/_geod.pyx
- pyproj/_proj.pyx
- pyproj/_transformer.pyx
- pyproj/base.pxi
> Remove deprecated PyObject_AsWriteBuffer

- docs/history.rst
- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/enums.py
- pyproj/proj.pxi
- test/test_crs.py
> Added from_name() to Ellipsoid, PrimeMeridian, CoordinateOperation, Datum

- docs/history.rst
- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/crs.py
- test/test_crs.py
> Fix getting Ellipsoid.semi_minor_metre when not computed

- pyproj/_crs.pyx
- test/test_crs.py
> Fix setting from_name with None as auth_name

- pyproj/_crs.pyx
- pyproj/crs/ellipsoid.py
- test/crs/test_crs.py
- test/crs/test_crs_ellipsoid.py
Related to: https://github.com/OSGeo/PROJ/issues/1866
Also updated Datum.from_name to only use legacy PROJ names under the PROJ or None authorities.
> added support in Ellipsoid.from_name for legacy PROJ names

- docs/api/crs/coordinate_operation.rst
- pyproj/crs/coordinate_operation.py
- test/crs/test_crs_coordinate_operation.py
> added StereographicConversion

- setup.py
> BUG: added pyproj.crs to packages

- docs/history.rst
- pyproj/_crs.pyx
- pyproj/crs/crs.py
- pyproj/enums.py
- pyproj/transformer.py
- test/crs/test_crs.py
> Added enumeration for WKT2_2019

- docs/api/crs/datum.rst
- pyproj/crs/datum.py
- test/crs/test_crs_datum.py
> ENH: Added custom prime meridian

- pyproj/crs/_cf1x8.py
- test/crs/test_crs_cf.py
> make lat_0 optional for geostationary & add warning for omerc when gamma lost

- pyproj/crs/crs.py
> add information about axis order changes to the +init= deprecation warning

- test/crs/test_crs.py
- test/test_transformer.py
Related to #531 
Fixes credit @sebastic (https://github.com/pyproj4/pyproj/issues/531#issuecomment-588394294)
> TST: Test fixes for PROJ 7

- docs/api/proj.rst
- docs/history.rst
- pyproj/_proj.pxd
- pyproj/_proj.pyx
- pyproj/proj.pxi
- pyproj/proj.py
- test/test_proj.py
The factors only work on a Proj object. So, should keep Proj around.
> ENH: Added Proj.get_factors()

- pyproj/geod.py
This PR improves the formatting of the docstrings of some methods of `geod.py`, as suggested here: https://github.com/pyproj4/pyproj/pull/550#issue-379596059
> Improve formatting of docstrings in geod.py

- docs/history.rst
- pyproj/_crs.pyx
- pyproj/crs/crs.py
- test/crs/test_crs.py
> ENH: Updated pyproj.crs.CRS.axis_info to pull all relevant axis information from CRS.

- pyproj/_crs.pyx
- test/crs/test_crs.py
> ENH: Added method name to CoordinateOperation repr

- pyproj/datadir.py
- pyproj/utils.py
- test/test_utils.py
> TST: Added tests for utilities

- docs/history.rst
- pyproj/crs/crs.py
- test/crs/test_crs.py
> ENH: Added pyproj.crs.CRS.utm_zone

- docs/history.rst
- pyproj/crs/crs.py
- test/test_proj.py
> bugfix re issue #564, numpy.bool_(False) is not False

- docs/history.rst
- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/test_transformer.py
> BUG: Fix pipeline transformations to match cct

- docs/advanced_examples.rst
> DOC: Added multithreading documentation

- docs/history.rst
- test/test_proj.py
- test/test_transformer.py
An assortment of small things.
- Doc related to #574 
- Test fix for i686 builds: https://travis-ci.com/github/pyproj4/pyproj-wheels/jobs/297624007
- Test for https://github.com/pyproj4/pyproj/pull/559#discussion_r386853911
> MISC: Test & history updates

- LICENSE
- docs/conf.py
- pyproj/__init__.py
- pyproj/compat.py
- pyproj/crs/__init__.py
- pyproj/crs/coordinate_operation.py
- pyproj/crs/coordinate_system.py
- pyproj/crs/crs.py
- pyproj/crs/datum.py
- pyproj/datadir.py
- pyproj/exceptions.py
- pyproj/geod.py
- pyproj/proj.py
- pyproj/transformer.py
- pyproj/utils.py
- setup.py
> Updated license & copyright information

- docs/history.rst
- pyproj/crs/_cf1x8.py
- test/crs/test_crs_cf.py
> BUG: Fix building prime meridian in pyproj.crs.CRS.from_cf

- docs/history.rst
- pyproj/crs/crs.py
- test/crs/test_crs.py
- test/test_proj.py
> BUG: Fix check for numpy bool True kwarg

- docs/history.rst
- pyproj/proj.py
- pyproj/transformer.py
> DOC: Update pyproj.Proj docstrings for clarity

- .isort.cfg
- .travis.yml
- pyproj/transformer.py
- test/conftest.py
- test/crs/test_crs.py
- test/test_datum.py
- test/test_doctest_wrapper.py
- test/test_transformer.py
https://github.com/conda-forge/pyproj-feedstock/pull/70
> TST: Update tests with behavior with new PROJ grids

- docs/history.rst
- pyproj/_proj.pyx
- test/test_proj.py
> BUG: Fix Proj.get_factors

- docs/crs_compatibility.rst
- docs/index.rst
> DOC: Added guide for CRS compatibility in python geospatial ecosystem

- docs/gotchas.rst
- pyproj/transformer.py
- test/test_datum.py
- test/test_datum_shift.py
- test/test_doctest_wrapper.py
- test/test_proj.py
- test/test_transform.py
- test/test_transformer.py
> Add deprecation warnings for transform/itransform functions

- .travis.yml
- test/test_transformer.py
> CI: 6.3.2 & 7.0.1 & update tests

- docs/gotchas.rst
> DOC: Add gotcha section for SQLite exceptions

- test/test_proj.py
> TST: Reduce precision for meridian parallel angle

- test/test_transformer.py
> TST: Focus test_transform_group__missing_best assertions on what matters

- docs/history.rst
- docs/transformation_grids.rst
- pyproj/_datadir.pxd
- pyproj/_datadir.pyx
- pyproj/_transformer.pyi
- pyproj/_transformer.pyx
- pyproj/proj.pxi
- pyproj/proj.py
- pyproj/transformer.py
- test/test_proj.py
- test/test_transformer.py
> ENH: Add network methods to Transformer

- docs/api/list.rst
- docs/history.rst
- pyproj/__init__.py
- pyproj/_list.pyi
- pyproj/_list.pyx
- pyproj/proj.pxi
- test/test_list.py
> ENH: Update get_units_map to be based on PROJ database & cleanup get_codes

- docs/history.rst
- pyproj/_transformer.pxd
- pyproj/_transformer.pyx
- pyproj/proj.pxi
- test/test_proj.py
- test/test_transformer.py
>  ENH: Add support for radians for Proj & Transformer.from_pipeline & use less gil

- .pre-commit-config.yaml
- pyproj/geod.py
- pyproj/transformer.py
- test/test_geod.py
- test/test_transformer.py
I've been forced to update `.pre-commit-config.yaml`
> Fix some calls to _convertback (#622)

- pyproj/_crs.pyx
- test/test_transformer.py
> BUG: Ensure network setting transferred to operations context

- docs/history.rst
- docs/transformation_grids.rst
- pyproj/_datadir.pyx
- pyproj/proj.pxi
- pyproj/transformer.py
- test/conftest.py
- test/test_datadir.py
- test/test_transformer.py
> ENH: Added TransformerGroup.download_grids

- .travis.yml
> Travis: Pin Python 3.7.2

- pyproj/sync.py
- test/test_sync.py
> ENH: Re-download files.geojson if 1 day old & use _download_resource_file

- pyproj/geod.py
> DOC: Update Geod.*_area_perimeter docstring & add note about signed areas

- docs/history.rst
- pyproj/_crs.pyx
- test/crs/test_crs.py
> BUG: Add support for identifying engineering/parametric/temporal datums

- appveyor.yml
From: https://github.com/OSGeo/PROJ/commit/b59fd03f1185c41015b25cbbf7a88a20825f8996
> CI: Appveyor vcpkg patch for VS2015

- docs/history.rst
- pyproj/crs/crs.py
- test/crs/test_crs_cf.py
> ENH: Add support for temporal CRS CF coordinate system

- pyproj/_datadir.pyx
- pytest.ini
- test/test_datadir.py
> BUG: Use static variable for user data directory for set_context_data_dir

- MANIFEST.in
- setup.py
Update according to: https://mypy.readthedocs.io/en/stable/installed_packages.html
> TYPE: PEP 561 compatibity updates

- .pre-commit-config.yaml
- pyproj/_crs.pyx
- pyproj/_datadir.pyx
- pyproj/_list.pyx
- pyproj/_transformer.pyx
Apparently cython is supported now :tada:
> ISORT v5 - cython support

- pyproj/network.py
- test/test_network.py
> Reset bundle path to use system settings/environment variables

- .pre-commit-config.yaml
- .stickler.yml
- Makefile
- pyproj/__main__.py
- pyproj/geod.py
- pyproj/sync.py
- pyproject.toml
- test/crs/test_crs.py
- test/crs/test_crs_cf.py
- test/test_cli.py
- test/test_list.py
- test/test_proj.py
- test/test_sync.py
- test/test_transformer.py
- test/test_utils.py
Looks like stickler is stuck on `19.10b0`
> BLK: Update to latest black & move target version to pyproject.toml

- test/test_transformer.py
From: https://travis-ci.com/github/pyproj4/pyproj/jobs/387514616
I believe it is related to: https://github.com/OSGeo/PROJ/pull/2357
> TST: Update order of transformations

- docs/api/database.rst
- docs/examples.rst
- docs/history.rst
- pyproj/database.pyx
- test/test_database.py
Background: https://github.com/geopandas/geopandas/issues/1528
> ENH: Added pyproj.database.query_utm_crs_info

- docs/examples.rst
- docs/gotchas.rst
- test/crs/test_crs.py
- test/test_cli.py
- test/test_datadir.py
- test/test_network.py
- test/test_proj.py
- test/test_sync.py
- test/test_transformer.py
Related to: https://github.com/OSGeo/PROJ/pull/2370
> TST: Update to EPSG 10

- docs/installation.rst
- pyproj/_crs.pyx
- pyproj/proj.pxi
- setup.py
- test/conftest.py
- test/crs/test_crs.py
- test/crs/test_crs_cf.py
The main goal is consistency. With PROJ 8+ preference for datums is given to the ensemble version.
> ENH: Add support for datum ensemble

- pytest.ini
- test/test_cli.py
- test/test_doctest_wrapper.py
- test/test_sync.py
- test/test_transformer.py
> TST: Add marker for tests that require the network enabled

- setup.cfg
> Do not include test package in wheels

- test/test_transformer.py
Ref: https://github.com/OSGeo/PROJ/issues/2425
> TST: Skip test_illegal_transformation with PROJ>=8

- docs/advanced_examples.rst
- docs/transformation_grids.rst
- pyproj/transformer.py
> DOC: Add warning for TransformerGroup.transform_grids

- docs/history.rst
- pyproj/_crs.pyx
- pyproj/utils.py
- test/crs/test_crs_cf.py
> BUG: support numpy objects in CRS.from_cf

- test/test_transformer.py
> TST: Update Transformer repr tests for PROJ 8 EPSG database updates

- docs/build_crs.rst
- test/conftest.py
- test/crs/test_crs.py
- test/crs/test_crs_cf.py
- test/crs/test_crs_maker.py
> TST: Handle rename of hayford ellipsoid in PROJ 8+

- test/test_datadir.py
- Identified in #772, related to https://github.com/OSGeo/PROJ/issues/2535
> TST: Handle error log with PROJ 8+

- test/crs/test_crs_cf.py
Resolves: https://github.com/pyproj4/pyproj/pull/783#discussion_r584543881
> TST: Remove use of deprecated numpy.int

- .github/workflows/tests.yaml
https://github.com/pyproj4/pyproj/issues/785#issuecomment-788590850
> CI: Add building manpages to doc tests

- docs/history.rst
- pyproj/aoi.py
- pyproj/utils.py
- test/test_aoi.py
> BUG: Disallow NaN values with AreaOfInterest & BBox

- docs/history.rst
- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/_transformer.pyi
- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/crs/test_crs.py
- test/test_transformer.py
> ENH: Pretty format PROJ string support & added Transformer.to_proj4

- pyproj/_transformer.pyx
- pyproj/proj.pxi
Needed for #754, alternative for #800.
> REF: Add custom proj_create_crs_to_crs to allow options

- docs/history.rst
- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/test_transformer.py
> ENH: Added support for AUTH:CODE input to pyproj.transformer.Transformer.from_pipeline

- pyproj/_transformer.pyi
- pyproj/_transformer.pyx
- pyproj/transformer.py
> TYP: Add typing for _Transformer._transform_bounds

- test/conftest.py
- test/crs/test_crs_cf.py
> TST: fix PROJ 8.0.1 test_osgb_1936

- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/test_transformer.py
> ENH: Add handling for antimeridian in Transformer.transform_bounds

- pyproj/_transformer.pyx
- test/test_transformer.py
And the edge cases keep coming.
> ENH: Transformer.transform_bounds - handle bounds bigger than -180/180

- test/test_transformer.py
> TST: Add transform_bounds tests for handling inf and radians

- test/conftest.py
- test/test_transformer.py
> TST: Update test_transform_group__area_of_interest for PROJ 8.1

- test/test_transformer.py
> TST: Update test_transformer__area_of_interest for PROJ 8.1

- test/test_transformer.py
Failures: https://github.com/pyproj4/pyproj/runs/2603509991
Related: https://github.com/OSGeo/PROJ/pull/2722
> TST: Update tests for EPSG v10.0.22

- docs/history.rst
- pyproj/_geod.pxd
- setup.py
> ENH: Allow cimport

- docs/advanced_examples.rst
- docs/api/network.rst
- docs/api/transformer.rst
- docs/conf.py
- docs/gotchas.rst
- docs/history.rst
- docs/installation.rst
- docs/transformation_grids.rst
- pyproj/_datadir.pyx
- pyproj/_transformer.pyx
- pyproj/crs/coordinate_operation.py
- pyproj/crs/crs.py
- pyproj/proj.py
- pyproj/transformer.py
Not perfect, but an improvement over what was there before.
> DOC: Intersphinx with PROJ

- pyproj/_crs.pyx
- pyproj/_datadir.pyx
- pyproj/_geod.pyx
- pyproj/_transformer.pyx
- pyproj/crs/coordinate_operation.py
- pyproj/crs/coordinate_system.py
- pyproj/crs/crs.py
- pyproj/crs/datum.py
- pyproj/database.pyx
- pyproj/geod.py
- pyproj/proj.py
- pyproj/sync.py
- pyproj/transformer.py
Also, some other random doc fixes in there.
> DOC: Use numpydoc style for parameter default syntax

- docs/history.rst
- pyproj/_datadir.pyx
- pyproj/proj.pxi
> REF: Handle deprecation of proj_context_set_autoclose_database

- .github/workflows/tests.yaml
- docs/history.rst
- pyproj/_compat.pyx
- pyproj/_geod.pyx
- pyproj/_transformer.pyx
- setup.py
> BUG: Add PyPy cython array implementation 

- docs/history.rst
- pyproj/_crs.pyx
- pyproj/proj.pxi
> BUG: Hide unnecessary PROJ ERROR from proj_crs_get_coordoperation

- pyproj/geod.py
> TST: Adjust geometry_area_perimeter docstring test sensitivity

- docs/api/crs/crs.rst
- docs/history.rst
- pyproj/crs/__init__.py
- pyproj/crs/crs.py
- test/crs/test_crs_maker.py
> ENH: Added pyproj.crs.GeocentricCRS

- .github/workflows/tests.yaml
- .pylintrc
- docs/history.rst
- pyproj/__init__.py
- pyproj/__main__.py
- pyproj/_show_versions.py
- pyproj/aoi.py
- pyproj/crs/__init__.py
- pyproj/crs/coordinate_operation.py
- pyproj/crs/crs.py
- pyproj/crs/datum.py
- pyproj/datadir.py
- pyproj/enums.py
- pyproj/geod.py
- pyproj/network.py
- pyproj/proj.py
- pyproj/sync.py
- pyproj/transformer.py
- pyproj/utils.py
- test/crs/test_crs.py
- test/crs/test_crs_cf.py
- test/test_aoi.py
- test/test_database.py
- test/test_doctest_wrapper.py
- test/test_geod.py
- test/test_list.py
- test/test_utils.py
> LNT: Add pylint & address issues

- pyproj/_crs.pxd
- pyproj/_crs.pyx
- pyproj/_network.pyx
- pyproj/_transformer.pyi
- pyproj/_transformer.pyx
- pyproj/database.pyx
- pyproj/proj.py
- pyproj/transformer.py
> REF: Additional type optimization

- pyproj/_crs.pyx
- pyproj/_datadir.pyx
- pyproj/_transformer.pyx
> REF: Additional typing of methods

- test/conftest.py
- test/crs/test_crs.py
- test/test_transformer.py
Related: https://github.com/OSGeo/PROJ/pull/2851
> TST: update tests for EPSG v10.035

- test/crs/test_crs_cf.py
https://github.com/OSGeo/PROJ/pull/2850
> TST: Update CF tests for PROJJSON Schema v4

- pyproj/_crs.pyx
- pyproj/geod.py
Well, we've all got to start somewhere...
... noticed some minor typos et al, so thought I'd suggest a change.
Thanks for `pyproj` btw, it's incredible! :beers:
> fix minor typos

- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/test_transformer.py
Idea from Evan [ref](https://github.com/OSGeo/PROJ/pull/2882#discussion_r719441160)
> BUG: Handle axis order with poles in transform bounds

- test/crs/test_crs.py
https://github.com/OSGeo/PROJ/pull/2872
> TST: test_datum__from_epsg update for EPSG v10.036

- docs/history.rst
- pyproj/_show_versions.py
- test/test_show_versions.py
> ENH: Added PROJ database metadata to pyproj.show_versions

- pyproj/crs/crs.py
Minor correction to `crs` doc-strings
> minor fix to crs doc-strings

- .github/workflows/wheels.yaml
- ci/proj-compile-wheels.sh
> CI: cibuildwheel linux

- test/conftest.py
- test/crs/test_crs.py
- test/crs/test_crs_cf.py
> TST: Update datum representations due to OSGeo/PROJ#3125 (PROJ 9.0.1+)

- test/crs/test_crs_maker.py
> TST: Update test_make_geographic_3d_crs for OGC:CRS84h

- .github/workflows/tests.yaml
> CI: Use PROJ docker for tests

- test/test_transformer.py
> TST: Update test_transformer_group__get_transform_crs for OSGeo/PROJ#3119

- .github/workflows/build_docs.yaml
- .github/workflows/test_proj_latest.yaml
- .github/workflows/tests.yaml
- .github/workflows/wheels.yaml
Related:
- https://github.com/OSGeo/gdal/pull/5460
- https://github.com/geopandas/geopandas/pull/2121
> CI: Cancel PR and branch workflows on new push

- .github/workflows/wheels.yaml
- HOW_TO_RELEASE.md
- Makefile
- appveyor.yml
> MNT: Update to use the build package & update release process

- .github/workflows/release.yaml
> CI: Add windows vcpkg build

- docs/conf.py
- pyproj/geod.py
- pyproj/proj.py
- pyproj/transformer.py
Not quite sure what a good solution would be to not repeat the list of accepted input everywhere.
> DOC: Add list of accepted inputs for scalar or array

- docs/transformation_grids.rst
While reading through the transformation grids documentation, I noticed a few issues which might need to be fixed.  Since all are associated with the transformation grids documentation, they all part of one PR.  Nevertheless, I've made several commits so that they can be cherry-picked as desired.
This PR is submitted in the hope that it is useful; if you have any questions, comments or wish for any changes, please don't hesitate to let me know :-)
> Fix issues in transformation grids docs

- .github/workflows/release.yaml
> CI: Upgrade MacOS whell actions runner

- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- docs/history.rst
- requirements-test.txt
- setup.cfg
> DEP: Add python 3.11 support

- test/test_sync.py
> TST: add no_kv to sync tests

- docs/conf.py
Added due to packaging issues with furo theme:
https://github.com/pyproj4/pyproj/discussions/1134#discussioncomment-3597580
> DOC: Add PYPROJ_HTML_THEME environment variable

- test/test_sync.py
> TST: update test_get_transform_grid_list__contains expected output

- test/test_transformer.py
> TST: adjust test_transformer_group__get_transform_crs for nl_nsgi_nlgeo2018 and PROJ 9.1

- .github/workflows/release.yaml
- requirements-test.txt
- test/test_doctest_wrapper.py
- test/test_geod.py
https://github.com/pyproj4/pyproj/issues/1064#issuecomment-1250615709
> TST: Handle OSError on shapely import

- CONTRIBUTING.md
- HOW_TO_RELEASE.md
- docs/advanced_examples.rst
- docs/examples.rst
- docs/gotchas.rst
- docs/history.rst
- pyproj/_crs.pyx
- pyproj/crs/_cf1x8.py
- pyproj/crs/crs.py
- pyproj/exceptions.py
- pyproj/network.py
- pyproj/transformer.py
- pyproj/utils.py
- test/crs/test_crs.py
- test/test_geod.py
- test/test_transformer.py
Really minor PR that only fixes a few typos. Feel free to close it if you don't think this is necessary.
> DOC: fix a few typos

- setup.cfg
> MNT: Use license_files in setup.cfg

- pyproj/transformer.py
- test/test_datum.py
- test/test_datum_shift.py
- test/test_doctest_wrapper.py
- test/test_proj.py
- test/test_transform.py
- test/test_transformer.py
This should be more visible and encourage better practice.
> MNT: Use FutureWarning for pyproj.transform|itransform

- test/conftest.py
- test/crs/test_crs.py
> TST: update test_coordinate_operation_grids__alternative_grid_name for PROJ 9.1.1

- .github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
Related #1171
> CI: Add dependabot for GitHub actions

- pyproj/_transformer.pyx
After #1123 length options should be increased
> BUG: Fix Transform options array length 

- test/test_sync.py
Related: https://github.com/OSGeo/PROJ-data/pull/90
> TST: Fix expected tranform grid list for bbox

- test/conftest.py
- test/test_geod.py
> TST:geod: Use scalar_and_array in fwd/inv tests

- pyproj/_crs.pyx
- pyproj/_geod.pyx
- pyproj/_transformer.pyx
Mostly code style preference ... trying it out.
Mainly for larger blocks of cdef statements.
> REF: Use cdef blocks

- test/test_transformer.py
> TST: Update test_transform_bounds__ignore_inf for PROJ 9.2+

- docs/history.rst
- pyproj/_transformer.pyi
- pyproj/_transformer.pyx
- pyproj/transformer.py
- test/test_transformer.py
> ENH: Added only_best kwarg to Transformer.from_crs

- test/test_transformer.py
> TST: Update transformer test_repr__conditional

- .github/workflows/tests.yaml
> CI: Use ghcr.io/osgeo/proj docker image

- test/test_transformer.py
> TST: Update test_transformer_group_allow_superseded_filter

- test/conftest.py
- test/test_transformer.py
https://github.com/pyproj4/pyproj/actions/runs/4663166612/jobs/8254239069
> TST: Update test_transformer_group_allow_superseded_filter PROJ version check

- test/conftest.py
- test/test_transformer.py
> TST: Make test_transformer_group_allow_superseded_filter relative comparison

- test/conftest.py
- test/crs/test_crs.py
https://github.com/OSGeo/PROJ/pull/3727
> TST: Fix test_datum_unknown

- test/test_transformer.py
https://github.com/OSGeo/PROJ/pull/3731
> TST: Fix transformer test_repr

- docs/history.rst
- setup.py
> BUG: Remove pkg_resources from setup.py

- .cirrus.yml
- .github/workflows/release.yaml
- https://github.com/scipy/oldest-supported-numpy/pull/78
- https://github.com/scipy/oldest-supported-numpy/issues/76
> CI: Address numpy installation issues on pypy

- .github/workflows/release.yaml
- ci/proj-compile-wheels.sh
- ci/vcpkg.json
- docs/history.rst
- [conda-forge](https://github.com/conda-forge/proj.4-feedstock/pull/141)
- [vcpkg](https://github.com/microsoft/vcpkg/commit/46542ddc124d692945b66cf6dda9876b9eef1dc3)
> WHL: Wheels contain PROJ 9.4.0

- .github/workflows/tests.yaml
As mentioned by @snowman2 in https://github.com/pyproj4/pyproj/issues/1390#issuecomment-2067054089
> Fix tests.yaml for CI

- test/conftest.py
- test/crs/test_crs.py
https://github.com/OSGeo/PROJ/pull/4079
> TST: test_coordinate_operation_grids__alternative_grid_name PROJ 9.4.1 compatibility

- .github/workflows/release.yaml
> CI: cibuildwheel@v2.19

- .github/workflows/release.yaml
- ci/vcpkg.json
- docs/history.rst
> WHL: PROJ 9.4.1

- .github/workflows/release.yaml
From: https://github.com/pyproj4/pyproj/issues/1425#issuecomment-2315963145
> MNT: Rename build -> python-build for release workflow

- test/crs/test_crs_cf.py
- test/crs/test_crs_coordinate_system.py
> TST: Add assert statements at the end of tests

- .github/workflows/release.yaml
- ci/vcpkg.json
- docs/history.rst
- https://github.com/microsoft/vcpkg/pull/42462
- https://github.com/OSGeo/PROJ/releases/tag/9.5.1
> WHL: Wheels contain PROJ 9.5.1

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- docs/history.rst
- docs/index.rst
- pyproject.toml
https://scientific-python.org/specs/spec-0000/
Support dropped Q4 2024.
> DEP: Python 3.11+
